## <u>Maritime Shipping Industry Data Analysis and Prediction</u>
### Chow Tsz Chun Samuel
### Phuc Thien Bao Nguyen, Peter
<br>

## Phase 3 - Objective(s)
- ### Use separate coding file for 53451, 534546 and 549305 Dataset
- ### Use each dataset full set to training
- ### both the training dataset and test set would perform feature selection
- ### From Phase 2 result, apply the test set unseen data to the best model with feature selection threshold get the predict result

In [2]:
!pip install pandas
!pip install matplotlib
!pip install numpy
!python -m pip install --upgrade pip
!pip install ipywidgets
!pip install xgboost

Requirement already satisfied: pandas in c:\users\demon\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\demon\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\demon\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\demon\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\demon\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\demon\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: matplotlib in c:\users\demon\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.23 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\demon\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: numpy in c:\users\demon\anaconda3\lib\site-packages (1.26.4)

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

Requirement already satisfied: ipywidgets in c:\users\demon\anaconda3\lib\site-packages (8.1.2)
Requirement already satisfied: comm>=0.1.3 in c:\users\demon\anaconda3\lib\site-packages (from ipywidgets) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in c:\users\demon\anaconda3\lib\site-packages (from ipywidgets) (8.27.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\demon\anaconda3\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.10 in c:\users\demon\anaconda3\lib\site-packages (from ipywidgets) (4.0.10)
Requirement already satisfied: jupyterlab-widgets~=3.0.10 in c:\users\demon\anaconda3\lib\site-packages (from ipywidgets) (3.0.10)
Requirement already satisfied: decorator in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.15.1)
Requirement already satisfied: stack-data in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6 in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (4.11.0)
Requirement already satisfied: colorama in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\demon\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\demon\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.5)
Requirement already satisfied: executing in c:\users\demon\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: asttokens in c:\users\demon\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\demon\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: six in c:\users\demon\anaconda3\lib\site-packages (from asttokens->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)
Requirement already satisfied: xgboost in c:\users\demon\anaconda3\lib\site-packages (2.1.2)
Requirement already satisfied: numpy in c:\users\demon\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\demon\anaconda3\lib\site-packages (from xgboost) (1.13.1)

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Markdown, display

## <font color='green'>This Code works on the (549305) Dataset and testset

In [5]:
dataset_name = '549305'
dataset_name_with_date = f"{dataset_name}_with_date"
dataset_file_name = f"{dataset_name}_shifted.csv"

dataset_test_name = f"{dataset_name}_testset"
dataset_test_with_date = f"{dataset_name}_Test_with_date"
dataset_test_file_name = f"test set/{dataset_name}_test.csv"

In [6]:
dataset = {
    dataset_name_with_date : pd.read_csv(dataset_file_name),
    dataset_test_with_date : pd.read_csv(dataset_test_file_name)
}

In [7]:
df_group = {
    dataset_name : dataset[dataset_name_with_date].drop(['date'], axis=1),
    dataset_test_name : dataset[dataset_test_with_date].drop(['date'], axis=1)
}

In [8]:
df_group[dataset_name]

,549305,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,...,547018,22788,10511218,528444,38498,19671,45145,98000,8852112,10952
0,110.59000,17663.99227,286.49502,18519.79,1.61,990.95000,16480.18185,100.00000,5.6875,16998.22387,...,283.19,1900.00,1.57,377,103.45742,111.50,3600321,0.6300,11.29,8.00623
1,129.03000,22289.85253,287.47990,19767.62,1.64,1142.95238,17102.74785,101.71544,5.9375,21575.22670,...,280.88,1890.00,1.57,382,105.10912,113.25,3272514,0.9000,11.31,8.20910
2,120.89000,26044.21218,286.05289,20584.50,1.61,1285.95652,17989.32158,107.52593,6.0000,25680.26122,...,278.58,2091.00,1.57,397,105.73986,112.40,3372011,1.1500,11.32,8.38826
3,124.32000,23480.27946,286.51762,20584.50,1.59,1281.83333,21825.75467,112.86937,6.0000,22358.25062,...,276.27,2029.00,1.56,330,103.99441,112.00,3482104,1.2400,11.32,8.66177
4,169.06000,27744.56063,287.31110,20498.74,1.56,1428.19048,21583.57754,112.86937,6.0000,29055.85285,...,271.66,2079.00,1.56,409,105.91260,116.50,3796788,1.6000,11.35,9.11050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,117.86636,42874.94231,685.42458,31937.50,5.17,935.14286,22581.04705,196.06418,5.0000,22915.71320,...,271.00,538.00,0.34,462,184.76796,346.75,14318130,2.8250,11.40,10.24245
283,98.68250,24406.13501,686.70010,29812.50,5.29,798.90909,29494.00242,196.34199,5.2500,13391.47337,...,266.00,533.45,0.61,471,184.86106,319.00,14324683,3.6875,11.49,10.45107
284,185.73955,17439.35227,687.53170,29750.00,5.29,755.90476,30245.58786,198.09863,5.2500,10659.15408,...,265.00,486.60,0.74,514,185.30908,314.80,15019362,3.9000,11.67,10.68618
285,213.32950,55879.34460,688.13642,29750.00,5.29,1146.18182,38101.47544,207.43823,5.2500,26286.06540,...,263.00,511.30,0.50,550,185.30908,296.25,15367007,4.2250,11.62,11.02928
286,160.17688,78888.58850,688.44041,29750.00,5.29,1332.09091,28035.72025,208.60797,5.2500,41662.66326,...,264.00,541.10,0.23,380,186.36921,286.00,15372433,3.7500,11.48,11.01312

In [9]:
df_group[dataset_test_name]

,549305,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,...,547018,22788,10511218,528444,38498,19671,45145,98000,8852112,10952
0,185.73955,55879.34460,688.13642,29750,5.29,1146.18182,38101.47544,207.43823,5.25,26286.06540,...,263,511.300,0.50,550,185.30908,296.25,15367007,4.225,11.62,11.02928
1,160.17688,51506.18509,689.12440,31375,5.29,1143.62500,37527.33070,209.61168,5.25,24873.31234,...,266,556.700,0.00,450,186.64852,289.20,16283632,4.360,11.48,10.53502
2,198.07810,54590.69486,690.33513,32500,5.19,1263.00000,64882.32089,218.29366,5.25,22076.19917,...,259,495.700,0.00,471,188.62539,280.75,17668523,6.550,11.66,10.52608
3,188.50429,48533.15456,691.24324,31600,4.65,1136.76191,45357.10943,219.83351,5.25,23047.19049,...,259,596.900,0.23,543,193.53065,272.50,19388528,6.000,11.81,10.89020
4,199.23600,53362.48483,691.94981,32275,4.65,1224.65000,45126.76142,223.50768,5.25,26894.34344,...,260,628.600,0.16,406,198.32977,264.50,20643853,5.975,11.70,10.60473
5,128.61143,29926.73353,692.61706,32460,4.53,923.42857,25471.35623,233.53328,5.00,12067.79634,...,259,643.614,0.15,332,198.88817,250.80,23959424,4.220,11.49,10.72250

## (B) Data Wrangling
<br>

### <b>(B1) <u>Data validation</u></b>
### The very first step after extraction is verifying the data on checking if included invalid value
### The dataset is clear without any NULL value

In [11]:
df_group[dataset_name].isnull().sum()

549305                                     0
69870                                      0
29845                                      0
69839+542292+542548+542544                 0
4164579                                    0
43515                                      0
49881                                      0
94884                                      0
14392                                      0
531097+543452+49696+51597+542904+544000    0
22809                                      0
21986                                      0
45390                                      0
51642+49780+531117+543508+544056+542960    0
11278870                                   0
534659                                     0
548430                                     0
22539                                      0
10743792                                   0
542928+544024+531125+543476+49700          0
547003                                     0
97726                                      0
10722105                                   0
19049                                      0
545301                                     0
548166                                     0
14948                                      0
69832                                      0
530423                                     0
541454                                     0
548434                                     0
43520                                      0
11279456                                   0
22807                                      0
56449                                      0
10509911                                   0
547018                                     0
22788                                      0
10511218                                   0
528444                                     0
38498                                      0
19671                                      0
45145                                      0
98000                                      0
8852112                                    0
10952                                      0
dtype: int64

In [12]:
df_group[dataset_test_name].isnull().sum()

549305                                     0
69870                                      0
29845                                      0
69839+542292+542548+542544                 0
4164579                                    0
43515                                      0
49881                                      0
94884                                      0
14392                                      0
531097+543452+49696+51597+542904+544000    0
22809                                      0
21986                                      0
45390                                      0
51642+49780+531117+543508+544056+542960    0
11278870                                   0
534659                                     0
548430                                     0
22539                                      0
10743792                                   0
542928+544024+531125+543476+49700          0
547003                                     0
97726                                      0
10722105                                   0
19049                                      0
545301                                     0
548166                                     0
14948                                      0
69832                                      0
530423                                     0
541454                                     0
548434                                     0
43520                                      0
11279456                                   0
22807                                      0
56449                                      0
10509911                                   0
547018                                     0
22788                                      0
10511218                                   0
528444                                     0
38498                                      0
19671                                      0
45145                                      0
98000                                      0
8852112                                    0
10952                                      0
dtype: int64

In [13]:
correlation = df_group[dataset_name].corr().round(2)

target = "549305"
thresholds = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
features_group_size = len(thresholds)

df_featureSelected = []
df_featureSelected_testset = []

target_correlation = correlation[target]

for i in range(features_group_size):
    features_above_threshold = target_correlation[abs(target_correlation) >= thresholds[i]].index.tolist()

    # Remove the target itself from the list
    features_above_threshold.remove(target)

    df_featureSelected.append(df_group[dataset_name].filter(items=features_above_threshold))
    df_featureSelected_testset.append(df_group[dataset_test_name].filter(items=features_above_threshold))

    display(df_featureSelected[-1])
    display(df_featureSelected_testset[-1])

,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,...,547018,22788,10511218,528444,38498,19671,45145,98000,8852112,10952
0,17663.99227,286.49502,18519.79,1.61,990.95000,16480.18185,100.00000,5.6875,16998.22387,2008.000,...,283.19,1900.00,1.57,377,103.45742,111.50,3600321,0.6300,11.29,8.00623
1,22289.85253,287.47990,19767.62,1.64,1142.95238,17102.74785,101.71544,5.9375,21575.22670,1861.000,...,280.88,1890.00,1.57,382,105.10912,113.25,3272514,0.9000,11.31,8.20910
2,26044.21218,286.05289,20584.50,1.61,1285.95652,17989.32158,107.52593,6.0000,25680.26122,2004.000,...,278.58,2091.00,1.57,397,105.73986,112.40,3372011,1.1500,11.32,8.38826
3,23480.27946,286.51762,20584.50,1.59,1281.83333,21825.75467,112.86937,6.0000,22358.25062,1977.000,...,276.27,2029.00,1.56,330,103.99441,112.00,3482104,1.2400,11.32,8.66177
4,27744.56063,287.31110,20498.74,1.56,1428.19048,21583.57754,112.86937,6.0000,29055.85285,2175.000,...,271.66,2079.00,1.56,409,105.91260,116.50,3796788,1.6000,11.35,9.11050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,42874.94231,685.42458,31937.50,5.17,935.14286,22581.04705,196.06418,5.0000,22915.71320,3961.550,...,271.00,538.00,0.34,462,184.76796,346.75,14318130,2.8250,11.40,10.24245
283,24406.13501,686.70010,29812.50,5.29,798.90909,29494.00242,196.34199,5.2500,13391.47337,3893.257,...,266.00,533.45,0.61,471,184.86106,319.00,14324683,3.6875,11.49,10.45107
284,17439.35227,687.53170,29750.00,5.29,755.90476,30245.58786,198.09863,5.2500,10659.15408,3861.336,...,265.00,486.60,0.74,514,185.30908,314.80,15019362,3.9000,11.67,10.68618
285,55879.34460,688.13642,29750.00,5.29,1146.18182,38101.47544,207.43823,5.2500,26286.06540,3824.365,...,263.00,511.30,0.50,550,185.30908,296.25,15367007,4.2250,11.62,11.02928
286,78888.58850,688.44041,29750.00,5.29,1332.09091,28035.72025,208.60797,5.2500,41662.66326,3852.402,...,264.00,541.10,0.23,380,186.36921,286.00,15372433,3.7500,11.48,11.01312

,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,...,547018,22788,10511218,528444,38498,19671,45145,98000,8852112,10952
0,55879.34460,688.13642,29750,5.29,1146.18182,38101.47544,207.43823,5.25,26286.06540,3824.365,...,263,511.300,0.50,550,185.30908,296.25,15367007,4.225,11.62,11.02928
1,51506.18509,689.12440,31375,5.29,1143.62500,37527.33070,209.61168,5.25,24873.31234,3773.526,...,266,556.700,0.00,450,186.64852,289.20,16283632,4.360,11.48,10.53502
2,54590.69486,690.33513,32500,5.19,1263.00000,64882.32089,218.29366,5.25,22076.19917,3573.818,...,259,495.700,0.00,471,188.62539,280.75,17668523,6.550,11.66,10.52608
3,48533.15456,691.24324,31600,4.65,1136.76191,45357.10943,219.83351,5.25,23047.19049,3435.805,...,259,596.900,0.23,543,193.53065,272.50,19388528,6.000,11.81,10.89020
4,53362.48483,691.94981,32275,4.65,1224.65000,45126.76142,223.50768,5.25,26894.34344,3466.773,...,260,628.600,0.16,406,198.32977,264.50,20643853,5.975,11.70,10.60473
5,29926.73353,692.61706,32460,4.53,923.42857,25471.35623,233.53328,5.00,12067.79634,3951.742,...,259,643.614,0.15,332,198.88817,250.80,23959424,4.220,11.49,10.72250

,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,...,56449,10509911,547018,10511218,528444,38498,45145,98000,8852112,10952
0,17663.99227,286.49502,18519.79,1.61,990.95000,16480.18185,100.00000,5.6875,16998.22387,2008.000,...,0.02079,10.18,283.19,1.57,377,103.45742,3600321,0.6300,11.29,8.00623
1,22289.85253,287.47990,19767.62,1.64,1142.95238,17102.74785,101.71544,5.9375,21575.22670,1861.000,...,0.03830,10.36,280.88,1.57,382,105.10912,3272514,0.9000,11.31,8.20910
2,26044.21218,286.05289,20584.50,1.61,1285.95652,17989.32158,107.52593,6.0000,25680.26122,2004.000,...,0.09428,10.18,278.58,1.57,397,105.73986,3372011,1.1500,11.32,8.38826
3,23480.27946,286.51762,20584.50,1.59,1281.83333,21825.75467,112.86937,6.0000,22358.25062,1977.000,...,0.14866,10.15,276.27,1.56,330,103.99441,3482104,1.2400,11.32,8.66177
4,27744.56063,287.31110,20498.74,1.56,1428.19048,21583.57754,112.86937,6.0000,29055.85285,2175.000,...,0.14519,10.24,271.66,1.56,409,105.91260,3796788,1.6000,11.35,9.11050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,42874.94231,685.42458,31937.50,5.17,935.14286,22581.04705,196.06418,5.0000,22915.71320,3961.550,...,0.15442,9.11,271.00,0.34,462,184.76796,14318130,2.8250,11.40,10.24245
283,24406.13501,686.70010,29812.50,5.29,798.90909,29494.00242,196.34199,5.2500,13391.47337,3893.257,...,0.11111,8.78,266.00,0.61,471,184.86106,14324683,3.6875,11.49,10.45107
284,17439.35227,687.53170,29750.00,5.29,755.90476,30245.58786,198.09863,5.2500,10659.15408,3861.336,...,0.09231,9.96,265.00,0.74,514,185.30908,15019362,3.9000,11.67,10.68618
285,55879.34460,688.13642,29750.00,5.29,1146.18182,38101.47544,207.43823,5.2500,26286.06540,3824.365,...,0.14832,8.92,263.00,0.50,550,185.30908,15367007,4.2250,11.62,11.02928
286,78888.58850,688.44041,29750.00,5.29,1332.09091,28035.72025,208.60797,5.2500,41662.66326,3852.402,...,0.13977,7.45,264.00,0.23,380,186.36921,15372433,3.7500,11.48,11.01312

,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,...,56449,10509911,547018,10511218,528444,38498,45145,98000,8852112,10952
0,55879.34460,688.13642,29750,5.29,1146.18182,38101.47544,207.43823,5.25,26286.06540,3824.365,...,0.14832,8.92,263,0.50,550,185.30908,15367007,4.225,11.62,11.02928
1,51506.18509,689.12440,31375,5.29,1143.62500,37527.33070,209.61168,5.25,24873.31234,3773.526,...,0.12616,7.68,266,0.00,450,186.64852,16283632,4.360,11.48,10.53502
2,54590.69486,690.33513,32500,5.19,1263.00000,64882.32089,218.29366,5.25,22076.19917,3573.818,...,0.12826,5.86,259,0.00,471,188.62539,17668523,6.550,11.66,10.52608
3,48533.15456,691.24324,31600,4.65,1136.76191,45357.10943,219.83351,5.25,23047.19049,3435.805,...,0.11705,7.96,259,0.23,543,193.53065,19388528,6.000,11.81,10.89020
4,53362.48483,691.94981,32275,4.65,1224.65000,45126.76142,223.50768,5.25,26894.34344,3466.773,...,0.13250,8.29,260,0.16,406,198.32977,20643853,5.975,11.70,10.60473
5,29926.73353,692.61706,32460,4.53,923.42857,25471.35623,233.53328,5.00,12067.79634,3951.742,...,0.18942,8.14,259,0.15,332,198.88817,23959424,4.220,11.49,10.72250

,69870,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,51642+49780+531117+543508+544056+542960,...,530423,43520,11279456,56449,10509911,547018,10511218,38498,98000,8852112
0,17663.99227,18519.79,1.61,990.95000,16480.18185,100.00000,5.6875,16998.22387,2008.000,15827.75916,...,4.26690,706.35000,3.33,0.02079,10.18,283.19,1.57,103.45742,0.6300,11.29
1,22289.85253,19767.62,1.64,1142.95238,17102.74785,101.71544,5.9375,21575.22670,1861.000,20167.28874,...,6.29880,802.14286,3.31,0.03830,10.36,280.88,1.57,105.10912,0.9000,11.31
2,26044.21218,20584.50,1.61,1285.95652,17989.32158,107.52593,6.0000,25680.26122,2004.000,26340.12330,...,4.34760,809.39130,3.32,0.09428,10.18,278.58,1.57,105.73986,1.1500,11.32
3,23480.27946,20584.50,1.59,1281.83333,21825.75467,112.86937,6.0000,22358.25062,1977.000,19864.75174,...,3.94940,896.61111,3.34,0.14866,10.15,276.27,1.56,103.99441,1.2400,11.32
4,27744.56063,20498.74,1.56,1428.19048,21583.57754,112.86937,6.0000,29055.85285,2175.000,23061.70301,...,3.59820,925.42857,3.40,0.14519,10.24,271.66,1.56,105.91260,1.6000,11.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,42874.94231,31937.50,5.17,935.14286,22581.04705,196.06418,5.0000,22915.71320,3961.550,44697.53927,...,2.00000,615.95238,15.33,0.15442,9.11,271.00,0.34,184.76796,2.8250,11.40
283,24406.13501,29812.50,5.29,798.90909,29494.00242,196.34199,5.2500,13391.47337,3893.257,23643.56070,...,2.00000,744.18182,12.97,0.11111,8.78,266.00,0.61,184.86106,3.6875,11.49
284,17439.35227,29750.00,5.29,755.90476,30245.58786,198.09863,5.2500,10659.15408,3861.336,14782.89969,...,2.00000,818.76191,14.38,0.09231,9.96,265.00,0.74,185.30908,3.9000,11.67
285,55879.34460,29750.00,5.29,1146.18182,38101.47544,207.43823,5.2500,26286.06540,3824.365,61152.72545,...,3.18182,777.86364,15.19,0.14832,8.92,263.00,0.50,185.30908,4.2250,11.62
286,78888.58850,29750.00,5.29,1332.09091,28035.72025,208.60797,5.2500,41662.66326,3852.402,79171.84680,...,5.72727,814.22727,14.71,0.13977,7.45,264.00,0.23,186.36921,3.7500,11.48

,69870,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,51642+49780+531117+543508+544056+542960,...,530423,43520,11279456,56449,10509911,547018,10511218,38498,98000,8852112
0,55879.34460,29750,5.29,1146.18182,38101.47544,207.43823,5.25,26286.06540,3824.365,61152.72545,...,3.18182,777.86364,15.19,0.14832,8.92,263,0.50,185.30908,4.225,11.62
1,51506.18509,31375,5.29,1143.62500,37527.33070,209.61168,5.25,24873.31234,3773.526,38775.57644,...,6.63158,895.81250,14.03,0.12616,7.68,266,0.00,186.64852,4.360,11.48
2,54590.69486,32500,5.19,1263.00000,64882.32089,218.29366,5.25,22076.19917,3573.818,52713.63105,...,7.61905,1101.23810,12.13,0.12826,5.86,259,0.00,188.62539,6.550,11.66
3,48533.15456,31600,4.65,1136.76191,45357.10943,219.83351,5.25,23047.19049,3435.805,45062.34165,...,3.66667,958.52381,12.17,0.11705,7.96,259,0.23,193.53065,6.000,11.81
4,53362.48483,32275,4.65,1224.65000,45126.76142,223.50768,5.25,26894.34344,3466.773,54943.79838,...,2.30000,844.90000,11.99,0.13250,8.29,260,0.16,198.32977,5.975,11.70
5,29926.73353,32460,4.53,923.42857,25471.35623,233.53328,5.00,12067.79634,3951.742,19763.27921,...,2.00000,647.33333,10.82,0.18942,8.14,259,0.15,198.88817,4.220,11.49

,69870,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,19049,14948,69832,43520,56449,38498,98000
0,17663.99227,18519.79,1.61,990.95000,16480.18185,100.00000,5.6875,16998.22387,2008.000,15827.75916,8.56,19677.60538,14143.40183,95.01436,6.21094,128.110,706.35000,0.02079,103.45742,0.6300
1,22289.85253,19767.62,1.64,1142.95238,17102.74785,101.71544,5.9375,21575.22670,1861.000,20167.28874,10.06,36590.02901,17124.75941,93.57675,6.32031,146.750,802.14286,0.03830,105.10912,0.9000
2,26044.21218,20584.50,1.61,1285.95652,17989.32158,107.52593,6.0000,25680.26122,2004.000,26340.12330,11.50,35199.29811,18825.15200,97.53243,6.41250,183.300,809.39130,0.09428,105.73986,1.1500
3,23480.27946,20584.50,1.59,1281.83333,21825.75467,112.86937,6.0000,22358.25062,1977.000,19864.75174,11.99,29974.32101,20536.52947,102.37925,6.53906,163.230,896.61111,0.14866,103.99441,1.2400
4,27744.56063,20498.74,1.56,1428.19048,21583.57754,112.86937,6.0000,29055.85285,2175.000,23061.70301,14.06,38831.03773,22776.86395,100.22159,6.92969,177.560,925.42857,0.14519,105.91260,1.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,42874.94231,31937.50,5.17,935.14286,22581.04705,196.06418,5.0000,22915.71320,3961.550,44697.53927,38.70,47081.54097,30341.09311,96.42801,5.83756,156.250,615.95238,0.15442,184.76796,2.8250
283,24406.13501,29812.50,5.29,798.90909,29494.00242,196.34199,5.2500,13391.47337,3893.257,23643.56070,31.59,17335.72804,28426.38688,96.56464,5.86707,125.000,744.18182,0.11111,184.86106,3.6875
284,17439.35227,29750.00,5.29,755.90476,30245.58786,198.09863,5.2500,10659.15408,3861.336,14782.89969,34.38,13019.16234,27019.14807,97.10953,5.89652,117.000,818.76191,0.09231,185.30908,3.9000
285,55879.34460,29750.00,5.29,1146.18182,38101.47544,207.43823,5.2500,26286.06540,3824.365,61152.72545,32.99,62156.44691,37770.81668,101.68788,5.89627,179.375,777.86364,0.14832,185.30908,4.2250
286,78888.58850,29750.00,5.29,1332.09091,28035.72025,208.60797,5.2500,41662.66326,3852.402,79171.84680,36.02,100894.32590,45735.62019,101.33028,5.83039,256.250,814.22727,0.13977,186.36921,3.7500

,69870,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,19049,14948,69832,43520,56449,38498,98000
0,55879.34460,29750,5.29,1146.18182,38101.47544,207.43823,5.25,26286.06540,3824.365,61152.72545,32.99,62156.44691,37770.81668,101.68788,5.89627,179.375,777.86364,0.14832,185.30908,4.225
1,51506.18509,31375,5.29,1143.62500,37527.33070,209.61168,5.25,24873.31234,3773.526,38775.57644,32.44,71153.58119,43901.24824,101.81782,5.71846,183.500,895.81250,0.12616,186.64852,4.360
2,54590.69486,32500,5.19,1263.00000,64882.32089,218.29366,5.25,22076.19917,3573.818,52713.63105,24.05,71098.17814,48309.62451,104.58467,5.64298,206.250,1101.23810,0.12826,188.62539,6.550
3,48533.15456,31600,4.65,1136.76191,45357.10943,219.83351,5.25,23047.19049,3435.805,45062.34165,24.01,51831.94661,40462.66012,102.66276,5.69505,191.875,958.52381,0.11705,193.53065,6.000
4,53362.48483,32275,4.65,1224.65000,45126.76142,223.50768,5.25,26894.34344,3466.773,54943.79838,22.97,77161.49992,39461.80300,101.46676,5.71310,171.875,844.90000,0.13250,198.32977,5.975
5,29926.73353,32460,4.53,923.42857,25471.35623,233.53328,5.00,12067.79634,3951.742,19763.27921,24.84,35783.99818,24891.33271,106.01782,5.26612,141.000,647.33333,0.18942,198.88817,4.220

,69870,69839+542292+542548+542544,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,19049,14948,69832,43520,56449,98000
0,17663.99227,18519.79,990.95000,16480.18185,100.00000,5.6875,16998.22387,15827.75916,8.56,19677.60538,14143.40183,95.01436,6.21094,128.110,706.35000,0.02079,0.6300
1,22289.85253,19767.62,1142.95238,17102.74785,101.71544,5.9375,21575.22670,20167.28874,10.06,36590.02901,17124.75941,93.57675,6.32031,146.750,802.14286,0.03830,0.9000
2,26044.21218,20584.50,1285.95652,17989.32158,107.52593,6.0000,25680.26122,26340.12330,11.50,35199.29811,18825.15200,97.53243,6.41250,183.300,809.39130,0.09428,1.1500
3,23480.27946,20584.50,1281.83333,21825.75467,112.86937,6.0000,22358.25062,19864.75174,11.99,29974.32101,20536.52947,102.37925,6.53906,163.230,896.61111,0.14866,1.2400
4,27744.56063,20498.74,1428.19048,21583.57754,112.86937,6.0000,29055.85285,23061.70301,14.06,38831.03773,22776.86395,100.22159,6.92969,177.560,925.42857,0.14519,1.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,42874.94231,31937.50,935.14286,22581.04705,196.06418,5.0000,22915.71320,44697.53927,38.70,47081.54097,30341.09311,96.42801,5.83756,156.250,615.95238,0.15442,2.8250
283,24406.13501,29812.50,798.90909,29494.00242,196.34199,5.2500,13391.47337,23643.56070,31.59,17335.72804,28426.38688,96.56464,5.86707,125.000,744.18182,0.11111,3.6875
284,17439.35227,29750.00,755.90476,30245.58786,198.09863,5.2500,10659.15408,14782.89969,34.38,13019.16234,27019.14807,97.10953,5.89652,117.000,818.76191,0.09231,3.9000
285,55879.34460,29750.00,1146.18182,38101.47544,207.43823,5.2500,26286.06540,61152.72545,32.99,62156.44691,37770.81668,101.68788,5.89627,179.375,777.86364,0.14832,4.2250
286,78888.58850,29750.00,1332.09091,28035.72025,208.60797,5.2500,41662.66326,79171.84680,36.02,100894.32590,45735.62019,101.33028,5.83039,256.250,814.22727,0.13977,3.7500

,69870,69839+542292+542548+542544,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,19049,14948,69832,43520,56449,98000
0,55879.34460,29750,1146.18182,38101.47544,207.43823,5.25,26286.06540,61152.72545,32.99,62156.44691,37770.81668,101.68788,5.89627,179.375,777.86364,0.14832,4.225
1,51506.18509,31375,1143.62500,37527.33070,209.61168,5.25,24873.31234,38775.57644,32.44,71153.58119,43901.24824,101.81782,5.71846,183.500,895.81250,0.12616,4.360
2,54590.69486,32500,1263.00000,64882.32089,218.29366,5.25,22076.19917,52713.63105,24.05,71098.17814,48309.62451,104.58467,5.64298,206.250,1101.23810,0.12826,6.550
3,48533.15456,31600,1136.76191,45357.10943,219.83351,5.25,23047.19049,45062.34165,24.01,51831.94661,40462.66012,102.66276,5.69505,191.875,958.52381,0.11705,6.000
4,53362.48483,32275,1224.65000,45126.76142,223.50768,5.25,26894.34344,54943.79838,22.97,77161.49992,39461.80300,101.46676,5.71310,171.875,844.90000,0.13250,5.975
5,29926.73353,32460,923.42857,25471.35623,233.53328,5.00,12067.79634,19763.27921,24.84,35783.99818,24891.33271,106.01782,5.26612,141.000,647.33333,0.18942,4.220

,69870,69839+542292+542548+542544,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,14948,69832,43520,56449
0,17663.99227,18519.79,990.95000,16480.18185,100.00000,5.6875,16998.22387,15827.75916,8.56,19677.60538,14143.40183,6.21094,128.110,706.35000,0.02079
1,22289.85253,19767.62,1142.95238,17102.74785,101.71544,5.9375,21575.22670,20167.28874,10.06,36590.02901,17124.75941,6.32031,146.750,802.14286,0.03830
2,26044.21218,20584.50,1285.95652,17989.32158,107.52593,6.0000,25680.26122,26340.12330,11.50,35199.29811,18825.15200,6.41250,183.300,809.39130,0.09428
3,23480.27946,20584.50,1281.83333,21825.75467,112.86937,6.0000,22358.25062,19864.75174,11.99,29974.32101,20536.52947,6.53906,163.230,896.61111,0.14866
4,27744.56063,20498.74,1428.19048,21583.57754,112.86937,6.0000,29055.85285,23061.70301,14.06,38831.03773,22776.86395,6.92969,177.560,925.42857,0.14519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,42874.94231,31937.50,935.14286,22581.04705,196.06418,5.0000,22915.71320,44697.53927,38.70,47081.54097,30341.09311,5.83756,156.250,615.95238,0.15442
283,24406.13501,29812.50,798.90909,29494.00242,196.34199,5.2500,13391.47337,23643.56070,31.59,17335.72804,28426.38688,5.86707,125.000,744.18182,0.11111
284,17439.35227,29750.00,755.90476,30245.58786,198.09863,5.2500,10659.15408,14782.89969,34.38,13019.16234,27019.14807,5.89652,117.000,818.76191,0.09231
285,55879.34460,29750.00,1146.18182,38101.47544,207.43823,5.2500,26286.06540,61152.72545,32.99,62156.44691,37770.81668,5.89627,179.375,777.86364,0.14832
286,78888.58850,29750.00,1332.09091,28035.72025,208.60797,5.2500,41662.66326,79171.84680,36.02,100894.32590,45735.62019,5.83039,256.250,814.22727,0.13977

,69870,69839+542292+542548+542544,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,14948,69832,43520,56449
0,55879.34460,29750,1146.18182,38101.47544,207.43823,5.25,26286.06540,61152.72545,32.99,62156.44691,37770.81668,5.89627,179.375,777.86364,0.14832
1,51506.18509,31375,1143.62500,37527.33070,209.61168,5.25,24873.31234,38775.57644,32.44,71153.58119,43901.24824,5.71846,183.500,895.81250,0.12616
2,54590.69486,32500,1263.00000,64882.32089,218.29366,5.25,22076.19917,52713.63105,24.05,71098.17814,48309.62451,5.64298,206.250,1101.23810,0.12826
3,48533.15456,31600,1136.76191,45357.10943,219.83351,5.25,23047.19049,45062.34165,24.01,51831.94661,40462.66012,5.69505,191.875,958.52381,0.11705
4,53362.48483,32275,1224.65000,45126.76142,223.50768,5.25,26894.34344,54943.79838,22.97,77161.49992,39461.80300,5.71310,171.875,844.90000,0.13250
5,29926.73353,32460,923.42857,25471.35623,233.53328,5.00,12067.79634,19763.27921,24.84,35783.99818,24891.33271,5.26612,141.000,647.33333,0.18942

,69870,43515,531097+543452+49696+51597+542904+544000,542928+544024+531125+543476+49700,97726,69832,43520
0,17663.99227,990.95000,16998.22387,19677.60538,14143.40183,128.110,706.35000
1,22289.85253,1142.95238,21575.22670,36590.02901,17124.75941,146.750,802.14286
2,26044.21218,1285.95652,25680.26122,35199.29811,18825.15200,183.300,809.39130
3,23480.27946,1281.83333,22358.25062,29974.32101,20536.52947,163.230,896.61111
4,27744.56063,1428.19048,29055.85285,38831.03773,22776.86395,177.560,925.42857
...,...,...,...,...,...,...,...
282,42874.94231,935.14286,22915.71320,47081.54097,30341.09311,156.250,615.95238
283,24406.13501,798.90909,13391.47337,17335.72804,28426.38688,125.000,744.18182
284,17439.35227,755.90476,10659.15408,13019.16234,27019.14807,117.000,818.76191
285,55879.34460,1146.18182,26286.06540,62156.44691,37770.81668,179.375,777.86364
286,78888.58850,1332.09091,41662.66326,100894.32590,45735.62019,256.250,814.22727

,69870,43515,531097+543452+49696+51597+542904+544000,542928+544024+531125+543476+49700,97726,69832,43520
0,55879.34460,1146.18182,26286.06540,62156.44691,37770.81668,179.375,777.86364
1,51506.18509,1143.62500,24873.31234,71153.58119,43901.24824,183.500,895.81250
2,54590.69486,1263.00000,22076.19917,71098.17814,48309.62451,206.250,1101.23810
3,48533.15456,1136.76191,23047.19049,51831.94661,40462.66012,191.875,958.52381
4,53362.48483,1224.65000,26894.34344,77161.49992,39461.80300,171.875,844.90000
5,29926.73353,923.42857,12067.79634,35783.99818,24891.33271,141.000,647.33333

,69870,43515,542928+544024+531125+543476+49700,97726,69832
0,17663.99227,990.95000,19677.60538,14143.40183,128.110
1,22289.85253,1142.95238,36590.02901,17124.75941,146.750
2,26044.21218,1285.95652,35199.29811,18825.15200,183.300
3,23480.27946,1281.83333,29974.32101,20536.52947,163.230
4,27744.56063,1428.19048,38831.03773,22776.86395,177.560
...,...,...,...,...,...
282,42874.94231,935.14286,47081.54097,30341.09311,156.250
283,24406.13501,798.90909,17335.72804,28426.38688,125.000
284,17439.35227,755.90476,13019.16234,27019.14807,117.000
285,55879.34460,1146.18182,62156.44691,37770.81668,179.375
286,78888.58850,1332.09091,100894.32590,45735.62019,256.250

,69870,43515,542928+544024+531125+543476+49700,97726,69832
0,55879.34460,1146.18182,62156.44691,37770.81668,179.375
1,51506.18509,1143.62500,71153.58119,43901.24824,183.500
2,54590.69486,1263.00000,71098.17814,48309.62451,206.250
3,48533.15456,1136.76191,51831.94661,40462.66012,191.875
4,53362.48483,1224.65000,77161.49992,39461.80300,171.875
5,29926.73353,923.42857,35783.99818,24891.33271,141.000

### <b>(B2) <u>Split X Features and y result</u></b>

In [15]:
# A list of different features selected input
Xs = df_featureSelected #df_group[dataset_name].iloc[:, 1:]
Xs_test = df_featureSelected_testset
print(type(Xs[0]))

<class 'pandas.core.frame.DataFrame'>

In [16]:
y = df_group[dataset_name].iloc[:, 0]
y

0      110.59000
1      129.03000
2      120.89000
3      124.32000
4      169.06000
         ...
282    117.86636
283     98.68250
284    185.73955
285    213.32950
286    160.17688
Name: 549305, Length: 287, dtype: float64

In [17]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\demon\anaconda3\lib\site-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\demon\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\demon\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\demon\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\demon\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

### <b>(B3) <u>Data Normalization</u></b>
#### Since the X Features data ranging from single digit to $10^5$ scale, it is essential to perform <font color="blue">Normalization</font>
<br>

### <font color="blue">Max Min Normalization</font> is chosen

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
bApplyNormalization = 1

norm_Xs = [df.copy() for df in Xs]
norm_Xs_test = [df.copy() for df in Xs_test]
print(type(Xs[0]))

if bApplyNormalization:
    for i in range(features_group_size):
        scalerMaxMin = MinMaxScaler(feature_range=(0, 1))
        scalerMaxMin_test = MinMaxScaler(feature_range=(0, 1))
        norm_Xs[i] = scalerMaxMin.fit_transform(Xs[i])
        norm_Xs_test[i] = scalerMaxMin_test.fit_transform(Xs_test[i])

<class 'pandas.core.frame.DataFrame'>

In [21]:
norm_Xs

[array([[0.14654257, 0.00263138, 0.10324805, ..., 0.        , 0.16891892,
         0.49445211],
        [0.19235877, 0.00507521, 0.16703489, ..., 0.04864865, 0.18243243,
         0.52837828],
        [0.22954332, 0.0015343 , 0.20879233, ..., 0.09369369, 0.18918919,
         0.5583394 ],
        ...,
        [0.14431765, 0.99774517, 0.67731629, ..., 0.58918919, 0.42567568,
         0.94262302],
        [0.52504132, 0.99924569, 0.67731629, ..., 0.64774775, 0.39189189,
         1.        ],
        [0.75293324, 1.        , 0.67731629, ..., 0.56216216, 0.2972973 ,
         0.99729755]]),
 array([[0.14654257, 0.00263138, 0.10324805, ..., 0.        , 0.16891892,
         0.49445211],
        [0.19235877, 0.00507521, 0.16703489, ..., 0.04864865, 0.18243243,
         0.52837828],
        [0.22954332, 0.0015343 , 0.20879233, ..., 0.09369369, 0.18918919,
         0.5583394 ],
        ...,
        [0.14431765, 0.99774517, 0.67731629, ..., 0.58918919, 0.42567568,
         0.94262302],
        [0.52504132, 0.99924569, 0.67731629, ..., 0.64774775, 0.39189189,
         1.        ],
        [0.75293324, 1.        , 0.67731629, ..., 0.56216216, 0.2972973 ,
         0.99729755]]),
 array([[0.14654257, 0.10324805, 0.03246753, ..., 0.04229988, 0.        ,
         0.16891892],
        [0.19235877, 0.16703489, 0.03896104, ..., 0.05381458, 0.04864865,
         0.18243243],
        [0.22954332, 0.20879233, 0.03246753, ..., 0.05821173, 0.09369369,
         0.18918919],
        ...,
        [0.14431765, 0.67731629, 0.82900433, ..., 0.61292245, 0.58918919,
         0.42567568],
        [0.52504132, 0.67731629, 0.82900433, ..., 0.61292245, 0.64774775,
         0.39189189],
        [0.75293324, 0.67731629, 0.82900433, ..., 0.62031307, 0.56216216,
         0.2972973 ]]),
 array([[0.14654257, 0.10324805, 0.03246753, ..., 0.51028936, 0.04229988,
         0.        ],
        [0.19235877, 0.16703489, 0.03896104, ..., 0.52750548, 0.05381458,
         0.04864865],
        [0.22954332, 0.20879233, 0.03246753, ..., 0.58254594, 0.05821173,
         0.09369369],
        ...,
        [0.14431765, 0.67731629, 0.82900433, ..., 0.580609  , 0.61292245,
         0.58918919],
        [0.52504132, 0.67731629, 0.82900433, ..., 0.63567896, 0.61292245,
         0.64774775],
        [0.75293324, 0.67731629, 0.82900433, ..., 0.62727246, 0.62031307,
         0.56216216]]),
 array([[0.14654257, 0.10324805, 0.21724007, ..., 0.22565039, 0.51028936,
         0.        ],
        [0.19235877, 0.16703489, 0.27502466, ..., 0.28451552, 0.52750548,
         0.04864865],
        [0.22954332, 0.20879233, 0.32938853, ..., 0.28896972, 0.58254594,
         0.09369369],
        ...,
        [0.14431765, 0.67731629, 0.12788624, ..., 0.294728  , 0.580609  ,
         0.58918919],
        [0.52504132, 0.67731629, 0.27625236, ..., 0.26959584, 0.63567896,
         0.64774775],
        [0.75293324, 0.67731629, 0.34692679, ..., 0.29194145, 0.62727246,
         0.56216216]]),
 array([[0.14654257, 0.10324805, 0.21724007, ..., 0.18470065, 0.22565039,
         0.51028936],
        [0.19235877, 0.16703489, 0.27502466, ..., 0.23571673, 0.28451552,
         0.52750548],
        [0.22954332, 0.20879233, 0.32938853, ..., 0.33575094, 0.28896972,
         0.58254594],
        ...,
        [0.14431765, 0.67731629, 0.12788624, ..., 0.15429353, 0.294728  ,
         0.580609  ],
        [0.52504132, 0.67731629, 0.27625236, ..., 0.32500855, 0.26959584,
         0.63567896],
        [0.75293324, 0.67731629, 0.34692679, ..., 0.53540883, 0.29194145,
         0.62727246]]),
 array([[0.14654257, 0.21724007, 0.18936111, ..., 0.13806843, 0.18470065,
         0.22565039],
        [0.19235877, 0.27502466, 0.24041434, ..., 0.17729507, 0.23571673,
         0.28451552],
        [0.22954332, 0.32938853, 0.28620309, ..., 0.19966767, 0.33575094,
         0.28896972],
        ...,
        [0.14431765, 0.12788624, 0.11865329, ..., 0.30747862, 0.15429353,
         0.294728  ],
        [0.52504132, 0.27625236, 0.2929604 , ..., 0.44894167, 0.32500855,
         0.26959584],
        [0.75293324, 0.34692679, 0.46447545, ..., 0.55373707, 0.53540883,
         0.29194145]]),
 array([[0.14654257, 0.21724007, 0.15127359, 0.13806843, 0.18470065],
        [0.19235877, 0.27502466, 0.26076721, 0.17729507, 0.23571673],
        [0.22954332, 0.32938853, 0.25176341, 0.19966767, 0.33575094],
        ...,
        [0.14431765, 0.12788624, 0.10816581, 0.30747862, 0.15429353],
        [0.52504132, 0.27625236, 0.42628812, 0.44894167, 0.32500855],
        [0.75293324, 0.34692679, 0.67708308, 0.55373707, 0.53540883]])]

In [22]:
norm_Xs_df = []
norm_Xs_test_df = []
for i in range(features_group_size):
    norm_Xs_df.append(pd.DataFrame(norm_Xs[i], columns=Xs[i].columns))
    norm_Xs_test_df.append(pd.DataFrame(norm_Xs_test[i], columns=Xs_test[i].columns))
    display(norm_Xs_df[-1])
    display(norm_Xs_test_df[-1])

,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,...,547018,22788,10511218,528444,38498,19671,45145,98000,8852112,10952
0,0.146543,0.002631,0.103248,0.032468,0.217240,0.196029,0.008188,0.947034,0.189361,0.110844,...,0.385079,0.553093,0.867403,0.293307,0.042300,0.000000,0.010758,0.000000,0.168919,0.494452
1,0.192359,0.005075,0.167035,0.038961,0.275025,0.202623,0.018371,0.989407,0.240414,0.052021,...,0.358278,0.549785,0.867403,0.303150,0.053815,0.004284,0.000000,0.048649,0.182432,0.528378
2,0.229543,0.001534,0.208792,0.032468,0.329389,0.212014,0.052861,1.000000,0.286203,0.109244,...,0.331593,0.616275,0.867403,0.332677,0.058212,0.002203,0.003265,0.093694,0.189189,0.558339
3,0.204149,0.002687,0.208792,0.028139,0.327821,0.252649,0.084580,1.000000,0.249148,0.098439,...,0.304792,0.595766,0.861878,0.200787,0.046043,0.001224,0.006878,0.109910,0.189189,0.604079
4,0.246384,0.004656,0.204408,0.021645,0.383460,0.250084,0.084580,1.000000,0.323855,0.177671,...,0.251305,0.612306,0.861878,0.356299,0.059416,0.012240,0.017205,0.174775,0.209459,0.679120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,0.396241,0.992517,0.789137,0.803030,0.196025,0.260649,0.578415,0.830508,0.255367,0.892577,...,0.243648,0.102547,0.187845,0.460630,0.609150,0.575887,0.362492,0.395495,0.243243,0.868418
283,0.213319,0.995682,0.680511,0.829004,0.144235,0.333870,0.580064,0.872881,0.149130,0.865249,...,0.185636,0.101042,0.337017,0.478346,0.609799,0.507956,0.362707,0.550901,0.304054,0.903305
284,0.144318,0.997745,0.677316,0.829004,0.127886,0.341831,0.590491,0.872881,0.118653,0.852475,...,0.174034,0.085544,0.408840,0.562992,0.612922,0.497674,0.385505,0.589189,0.425676,0.942623
285,0.525041,0.999246,0.677316,0.829004,0.276252,0.425040,0.645930,0.872881,0.292960,0.837681,...,0.150830,0.093715,0.276243,0.633858,0.612922,0.452264,0.396914,0.647748,0.391892,1.000000
286,0.752933,1.000000,0.677316,0.829004,0.346927,0.318424,0.652873,0.872881,0.464475,0.848900,...,0.162432,0.103573,0.127072,0.299213,0.620313,0.427173,0.397092,0.562162,0.297297,0.997298

,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,...,547018,22788,10511218,528444,38498,19671,45145,98000,8852112,10952
0,1.000000,0.000000,0.000000,1.000000,0.655983,0.320472,0.000000,1.0,0.958974,0.753115,...,0.571429,0.105467,1.00,1.000000,0.000000,1.000000,0.000000,0.002146,0.424242,1.000000
1,0.831494,0.220500,0.590909,1.000000,0.648454,0.305904,0.083290,1.0,0.863688,0.654578,...,1.000000,0.412402,0.00,0.541284,0.098640,0.844884,0.106678,0.060086,0.000000,0.017766
2,0.950346,0.490713,1.000000,0.868421,1.000000,1.000000,0.415996,1.0,0.675033,0.267500,...,0.000000,0.000000,0.00,0.637615,0.244222,0.658966,0.267854,1.000000,0.545455,0.000000
3,0.716938,0.693388,0.672727,0.157895,0.628243,0.504574,0.475005,1.0,0.740523,0.000000,...,0.000000,0.684181,0.46,0.967890,0.605458,0.477448,0.468031,0.763948,1.000000,0.723609
4,0.903021,0.851082,0.918182,0.157895,0.887064,0.498729,0.615805,1.0,1.000000,0.060023,...,0.142857,0.898495,0.32,0.339450,0.958878,0.301430,0.614128,0.753219,0.666667,0.156300
5,0.000000,1.000000,0.985455,0.000000,0.000000,0.000000,1.000000,0.0,0.000000,1.000000,...,0.000000,1.000000,0.30,0.000000,1.000000,0.000000,1.000000,0.000000,0.030303,0.390342

,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,...,56449,10509911,547018,10511218,528444,38498,45145,98000,8852112,10952
0,0.146543,0.002631,0.103248,0.032468,0.217240,0.196029,0.008188,0.947034,0.189361,0.110844,...,0.510289,0.465347,0.385079,0.867403,0.293307,0.042300,0.010758,0.000000,0.168919,0.494452
1,0.192359,0.005075,0.167035,0.038961,0.275025,0.202623,0.018371,0.989407,0.240414,0.052021,...,0.527505,0.490806,0.358278,0.867403,0.303150,0.053815,0.000000,0.048649,0.182432,0.528378
2,0.229543,0.001534,0.208792,0.032468,0.329389,0.212014,0.052861,1.000000,0.286203,0.109244,...,0.582546,0.465347,0.331593,0.867403,0.332677,0.058212,0.003265,0.093694,0.189189,0.558339
3,0.204149,0.002687,0.208792,0.028139,0.327821,0.252649,0.084580,1.000000,0.249148,0.098439,...,0.636013,0.461103,0.304792,0.861878,0.200787,0.046043,0.006878,0.109910,0.189189,0.604079
4,0.246384,0.004656,0.204408,0.021645,0.383460,0.250084,0.084580,1.000000,0.323855,0.177671,...,0.632601,0.473833,0.251305,0.861878,0.356299,0.059416,0.017205,0.174775,0.209459,0.679120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,0.396241,0.992517,0.789137,0.803030,0.196025,0.260649,0.578415,0.830508,0.255367,0.892577,...,0.641677,0.314003,0.243648,0.187845,0.460630,0.609150,0.362492,0.395495,0.243243,0.868418
283,0.213319,0.995682,0.680511,0.829004,0.144235,0.333870,0.580064,0.872881,0.149130,0.865249,...,0.599093,0.267327,0.185636,0.337017,0.478346,0.609799,0.362707,0.550901,0.304054,0.903305
284,0.144318,0.997745,0.677316,0.829004,0.127886,0.341831,0.590491,0.872881,0.118653,0.852475,...,0.580609,0.434229,0.174034,0.408840,0.562992,0.612922,0.385505,0.589189,0.425676,0.942623
285,0.525041,0.999246,0.677316,0.829004,0.276252,0.425040,0.645930,0.872881,0.292960,0.837681,...,0.635679,0.287129,0.150830,0.276243,0.633858,0.612922,0.396914,0.647748,0.391892,1.000000
286,0.752933,1.000000,0.677316,0.829004,0.346927,0.318424,0.652873,0.872881,0.464475,0.848900,...,0.627272,0.079208,0.162432,0.127072,0.299213,0.620313,0.397092,0.562162,0.297297,0.997298

,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,...,56449,10509911,547018,10511218,528444,38498,45145,98000,8852112,10952
0,1.000000,0.000000,0.000000,1.000000,0.655983,0.320472,0.000000,1.0,0.958974,0.753115,...,0.432085,1.000000,0.571429,1.00,1.000000,0.000000,0.000000,0.002146,0.424242,1.000000
1,0.831494,0.220500,0.590909,1.000000,0.648454,0.305904,0.083290,1.0,0.863688,0.654578,...,0.125881,0.594771,1.000000,0.00,0.541284,0.098640,0.106678,0.060086,0.000000,0.017766
2,0.950346,0.490713,1.000000,0.868421,1.000000,1.000000,0.415996,1.0,0.675033,0.267500,...,0.154898,0.000000,0.000000,0.00,0.637615,0.244222,0.267854,1.000000,0.545455,0.000000
3,0.716938,0.693388,0.672727,0.157895,0.628243,0.504574,0.475005,1.0,0.740523,0.000000,...,0.000000,0.686275,0.000000,0.46,0.967890,0.605458,0.468031,0.763948,1.000000,0.723609
4,0.903021,0.851082,0.918182,0.157895,0.887064,0.498729,0.615805,1.0,1.000000,0.060023,...,0.213486,0.794118,0.142857,0.32,0.339450,0.958878,0.614128,0.753219,0.666667,0.156300
5,0.000000,1.000000,0.985455,0.000000,0.000000,0.000000,1.000000,0.0,0.000000,1.000000,...,1.000000,0.745098,0.000000,0.30,0.000000,1.000000,1.000000,0.000000,0.030303,0.390342

,69870,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,51642+49780+531117+543508+544056+542960,...,530423,43520,11279456,56449,10509911,547018,10511218,38498,98000,8852112
0,0.146543,0.103248,0.032468,0.217240,0.196029,0.008188,0.947034,0.189361,0.110844,0.116042,...,0.280717,0.225650,0.022265,0.510289,0.465347,0.385079,0.867403,0.042300,0.000000,0.168919
1,0.192359,0.167035,0.038961,0.275025,0.202623,0.018371,0.989407,0.240414,0.052021,0.149358,...,0.414395,0.284516,0.020992,0.527505,0.490806,0.358278,0.867403,0.053815,0.048649,0.182432
2,0.229543,0.208792,0.032468,0.329389,0.212014,0.052861,1.000000,0.286203,0.109244,0.196749,...,0.286026,0.288970,0.021628,0.582546,0.465347,0.331593,0.867403,0.058212,0.093694,0.189189
3,0.204149,0.208792,0.028139,0.327821,0.252649,0.084580,1.000000,0.249148,0.098439,0.147035,...,0.259829,0.342567,0.022901,0.636013,0.461103,0.304792,0.861878,0.046043,0.109910,0.189189
4,0.246384,0.204408,0.021645,0.383460,0.250084,0.084580,1.000000,0.323855,0.177671,0.171579,...,0.236724,0.360275,0.026718,0.632601,0.473833,0.251305,0.861878,0.059416,0.174775,0.209459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,0.396241,0.789137,0.803030,0.196025,0.260649,0.578415,0.830508,0.255367,0.892577,0.337685,...,0.131579,0.170101,0.785623,0.641677,0.314003,0.243648,0.187845,0.609150,0.395495,0.243243
283,0.213319,0.680511,0.829004,0.144235,0.333870,0.580064,0.872881,0.149130,0.865249,0.176046,...,0.131579,0.248898,0.635496,0.599093,0.267327,0.185636,0.337017,0.609799,0.550901,0.304054
284,0.144318,0.677316,0.829004,0.127886,0.341831,0.590491,0.872881,0.118653,0.852475,0.108020,...,0.131579,0.294728,0.725191,0.580609,0.434229,0.174034,0.408840,0.612922,0.589189,0.425676
285,0.525041,0.677316,0.829004,0.276252,0.425040,0.645930,0.872881,0.292960,0.837681,0.464017,...,0.209330,0.269596,0.776718,0.635679,0.287129,0.150830,0.276243,0.612922,0.647748,0.391892
286,0.752933,0.677316,0.829004,0.346927,0.318424,0.652873,0.872881,0.464475,0.848900,0.602355,...,0.376794,0.291941,0.746183,0.627272,0.079208,0.162432,0.127072,0.620313,0.562162,0.297297

,69870,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,51642+49780+531117+543508+544056+542960,...,530423,43520,11279456,56449,10509911,547018,10511218,38498,98000,8852112
0,1.000000,0.000000,1.000000,0.655983,0.320472,0.000000,1.0,0.958974,0.753115,1.000000,...,0.210324,0.287572,1.000000,0.432085,1.000000,0.571429,1.00,0.000000,0.002146,0.424242
1,0.831494,0.590909,1.000000,0.648454,0.305904,0.083290,1.0,0.863688,0.654578,0.459351,...,0.824264,0.547426,0.734554,0.125881,0.594771,1.000000,0.00,0.098640,0.060086,0.000000
2,0.950346,1.000000,0.868421,1.000000,1.000000,0.415996,1.0,0.675033,0.267500,0.796105,...,1.000000,1.000000,0.299771,0.154898,0.000000,0.000000,0.00,0.244222,1.000000,0.545455
3,0.716938,0.672727,0.157895,0.628243,0.504574,0.475005,1.0,0.740523,0.000000,0.611244,...,0.296611,0.685585,0.308924,0.000000,0.686275,0.000000,0.46,0.605458,0.763948,1.000000
4,0.903021,0.918182,0.157895,0.887064,0.498729,0.615805,1.0,1.000000,0.060023,0.849988,...,0.053390,0.435260,0.267735,0.213486,0.794118,0.142857,0.32,0.958878,0.753219,0.666667
5,0.000000,0.985455,0.000000,0.000000,0.000000,1.000000,0.0,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.745098,0.000000,0.30,1.000000,0.000000,0.030303

,69870,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,19049,14948,69832,43520,56449,38498,98000
0,0.146543,0.103248,0.032468,0.217240,0.196029,0.008188,0.947034,0.189361,0.110844,0.116042,0.000000,0.151274,0.138068,0.340244,0.890478,0.184701,0.225650,0.510289,0.042300,0.000000
1,0.192359,0.167035,0.038961,0.275025,0.202623,0.018371,0.989407,0.240414,0.052021,0.149358,0.047066,0.260767,0.177295,0.313910,0.906550,0.235717,0.284516,0.527505,0.053815,0.048649
2,0.229543,0.208792,0.032468,0.329389,0.212014,0.052861,1.000000,0.286203,0.109244,0.196749,0.092250,0.251763,0.199668,0.386370,0.920097,0.335751,0.288970,0.582546,0.058212,0.093694
3,0.204149,0.208792,0.028139,0.327821,0.252649,0.084580,1.000000,0.249148,0.098439,0.147035,0.107625,0.217936,0.222185,0.475154,0.938695,0.280821,0.342567,0.636013,0.046043,0.109910
4,0.246384,0.204408,0.021645,0.383460,0.250084,0.084580,1.000000,0.323855,0.177671,0.171579,0.172576,0.275276,0.251662,0.435630,0.996097,0.320041,0.360275,0.632601,0.059416,0.174775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,0.396241,0.789137,0.803030,0.196025,0.260649,0.578415,0.830508,0.255367,0.892577,0.337685,0.945717,0.328691,0.351186,0.366139,0.835611,0.261717,0.170101,0.641677,0.609150,0.395495
283,0.213319,0.680511,0.829004,0.144235,0.333870,0.580064,0.872881,0.149130,0.865249,0.176046,0.722623,0.136112,0.325994,0.368642,0.839947,0.176189,0.248898,0.599093,0.609799,0.550901
284,0.144318,0.677316,0.829004,0.127886,0.341831,0.590491,0.872881,0.118653,0.852475,0.108020,0.810166,0.108166,0.307479,0.378623,0.844275,0.154294,0.294728,0.580609,0.612922,0.589189
285,0.525041,0.677316,0.829004,0.276252,0.425040,0.645930,0.872881,0.292960,0.837681,0.464017,0.766552,0.426288,0.448942,0.462489,0.844238,0.325009,0.269596,0.635679,0.612922,0.647748
286,0.752933,0.677316,0.829004,0.346927,0.318424,0.652873,0.872881,0.464475,0.848900,0.602355,0.861625,0.677083,0.553737,0.455939,0.834557,0.535409,0.291941,0.627272,0.620313,0.562162

,69870,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,19049,14948,69832,43520,56449,38498,98000
0,1.000000,0.000000,1.000000,0.655983,0.320472,0.000000,1.0,0.958974,0.753115,1.000000,1.000000,0.637362,0.549975,0.048586,1.000000,0.588123,0.287572,0.432085,0.000000,0.002146
1,0.831494,0.590909,1.000000,0.648454,0.305904,0.083290,1.0,0.863688,0.654578,0.459351,0.945110,0.854802,0.811755,0.077138,0.717829,0.651341,0.547426,0.125881,0.098640,0.060086
2,0.950346,1.000000,0.868421,1.000000,1.000000,0.415996,1.0,0.675033,0.267500,0.796105,0.107784,0.853463,1.000000,0.685095,0.598048,1.000000,1.000000,0.154898,0.244222,1.000000
3,0.716938,0.672727,0.157895,0.628243,0.504574,0.475005,1.0,0.740523,0.000000,0.611244,0.103792,0.387842,0.664922,0.262796,0.680679,0.779693,0.685585,0.000000,0.605458,0.763948
4,0.903021,0.918182,0.157895,0.887064,0.498729,0.615805,1.0,1.000000,0.060023,0.849988,0.000000,1.000000,0.622183,0.000000,0.709323,0.473180,0.435260,0.213486,0.958878,0.753219
5,0.000000,0.985455,0.000000,0.000000,0.000000,1.000000,0.0,0.000000,1.000000,0.000000,0.186627,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000

,69870,69839+542292+542548+542544,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,19049,14948,69832,43520,56449,98000
0,0.146543,0.103248,0.217240,0.196029,0.008188,0.947034,0.189361,0.116042,0.000000,0.151274,0.138068,0.340244,0.890478,0.184701,0.225650,0.510289,0.000000
1,0.192359,0.167035,0.275025,0.202623,0.018371,0.989407,0.240414,0.149358,0.047066,0.260767,0.177295,0.313910,0.906550,0.235717,0.284516,0.527505,0.048649
2,0.229543,0.208792,0.329389,0.212014,0.052861,1.000000,0.286203,0.196749,0.092250,0.251763,0.199668,0.386370,0.920097,0.335751,0.288970,0.582546,0.093694
3,0.204149,0.208792,0.327821,0.252649,0.084580,1.000000,0.249148,0.147035,0.107625,0.217936,0.222185,0.475154,0.938695,0.280821,0.342567,0.636013,0.109910
4,0.246384,0.204408,0.383460,0.250084,0.084580,1.000000,0.323855,0.171579,0.172576,0.275276,0.251662,0.435630,0.996097,0.320041,0.360275,0.632601,0.174775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,0.396241,0.789137,0.196025,0.260649,0.578415,0.830508,0.255367,0.337685,0.945717,0.328691,0.351186,0.366139,0.835611,0.261717,0.170101,0.641677,0.395495
283,0.213319,0.680511,0.144235,0.333870,0.580064,0.872881,0.149130,0.176046,0.722623,0.136112,0.325994,0.368642,0.839947,0.176189,0.248898,0.599093,0.550901
284,0.144318,0.677316,0.127886,0.341831,0.590491,0.872881,0.118653,0.108020,0.810166,0.108166,0.307479,0.378623,0.844275,0.154294,0.294728,0.580609,0.589189
285,0.525041,0.677316,0.276252,0.425040,0.645930,0.872881,0.292960,0.464017,0.766552,0.426288,0.448942,0.462489,0.844238,0.325009,0.269596,0.635679,0.647748
286,0.752933,0.677316,0.346927,0.318424,0.652873,0.872881,0.464475,0.602355,0.861625,0.677083,0.553737,0.455939,0.834557,0.535409,0.291941,0.627272,0.562162

,69870,69839+542292+542548+542544,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,19049,14948,69832,43520,56449,98000
0,1.000000,0.000000,0.655983,0.320472,0.000000,1.0,0.958974,1.000000,1.000000,0.637362,0.549975,0.048586,1.000000,0.588123,0.287572,0.432085,0.002146
1,0.831494,0.590909,0.648454,0.305904,0.083290,1.0,0.863688,0.459351,0.945110,0.854802,0.811755,0.077138,0.717829,0.651341,0.547426,0.125881,0.060086
2,0.950346,1.000000,1.000000,1.000000,0.415996,1.0,0.675033,0.796105,0.107784,0.853463,1.000000,0.685095,0.598048,1.000000,1.000000,0.154898,1.000000
3,0.716938,0.672727,0.628243,0.504574,0.475005,1.0,0.740523,0.611244,0.103792,0.387842,0.664922,0.262796,0.680679,0.779693,0.685585,0.000000,0.763948
4,0.903021,0.918182,0.887064,0.498729,0.615805,1.0,1.000000,0.849988,0.000000,1.000000,0.622183,0.000000,0.709323,0.473180,0.435260,0.213486,0.753219
5,0.000000,0.985455,0.000000,0.000000,1.000000,0.0,0.000000,0.000000,0.186627,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000

,69870,69839+542292+542548+542544,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,14948,69832,43520,56449
0,0.146543,0.103248,0.217240,0.196029,0.008188,0.947034,0.189361,0.116042,0.000000,0.151274,0.138068,0.890478,0.184701,0.225650,0.510289
1,0.192359,0.167035,0.275025,0.202623,0.018371,0.989407,0.240414,0.149358,0.047066,0.260767,0.177295,0.906550,0.235717,0.284516,0.527505
2,0.229543,0.208792,0.329389,0.212014,0.052861,1.000000,0.286203,0.196749,0.092250,0.251763,0.199668,0.920097,0.335751,0.288970,0.582546
3,0.204149,0.208792,0.327821,0.252649,0.084580,1.000000,0.249148,0.147035,0.107625,0.217936,0.222185,0.938695,0.280821,0.342567,0.636013
4,0.246384,0.204408,0.383460,0.250084,0.084580,1.000000,0.323855,0.171579,0.172576,0.275276,0.251662,0.996097,0.320041,0.360275,0.632601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,0.396241,0.789137,0.196025,0.260649,0.578415,0.830508,0.255367,0.337685,0.945717,0.328691,0.351186,0.835611,0.261717,0.170101,0.641677
283,0.213319,0.680511,0.144235,0.333870,0.580064,0.872881,0.149130,0.176046,0.722623,0.136112,0.325994,0.839947,0.176189,0.248898,0.599093
284,0.144318,0.677316,0.127886,0.341831,0.590491,0.872881,0.118653,0.108020,0.810166,0.108166,0.307479,0.844275,0.154294,0.294728,0.580609
285,0.525041,0.677316,0.276252,0.425040,0.645930,0.872881,0.292960,0.464017,0.766552,0.426288,0.448942,0.844238,0.325009,0.269596,0.635679
286,0.752933,0.677316,0.346927,0.318424,0.652873,0.872881,0.464475,0.602355,0.861625,0.677083,0.553737,0.834557,0.535409,0.291941,0.627272

,69870,69839+542292+542548+542544,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,51642+49780+531117+543508+544056+542960,11278870,542928+544024+531125+543476+49700,97726,14948,69832,43520,56449
0,1.000000,0.000000,0.655983,0.320472,0.000000,1.0,0.958974,1.000000,1.000000,0.637362,0.549975,1.000000,0.588123,0.287572,0.432085
1,0.831494,0.590909,0.648454,0.305904,0.083290,1.0,0.863688,0.459351,0.945110,0.854802,0.811755,0.717829,0.651341,0.547426,0.125881
2,0.950346,1.000000,1.000000,1.000000,0.415996,1.0,0.675033,0.796105,0.107784,0.853463,1.000000,0.598048,1.000000,1.000000,0.154898
3,0.716938,0.672727,0.628243,0.504574,0.475005,1.0,0.740523,0.611244,0.103792,0.387842,0.664922,0.680679,0.779693,0.685585,0.000000
4,0.903021,0.918182,0.887064,0.498729,0.615805,1.0,1.000000,0.849988,0.000000,1.000000,0.622183,0.709323,0.473180,0.435260,0.213486
5,0.000000,0.985455,0.000000,0.000000,1.000000,0.0,0.000000,0.000000,0.186627,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000

,69870,43515,531097+543452+49696+51597+542904+544000,542928+544024+531125+543476+49700,97726,69832,43520
0,0.146543,0.217240,0.189361,0.151274,0.138068,0.184701,0.225650
1,0.192359,0.275025,0.240414,0.260767,0.177295,0.235717,0.284516
2,0.229543,0.329389,0.286203,0.251763,0.199668,0.335751,0.288970
3,0.204149,0.327821,0.249148,0.217936,0.222185,0.280821,0.342567
4,0.246384,0.383460,0.323855,0.275276,0.251662,0.320041,0.360275
...,...,...,...,...,...,...,...
282,0.396241,0.196025,0.255367,0.328691,0.351186,0.261717,0.170101
283,0.213319,0.144235,0.149130,0.136112,0.325994,0.176189,0.248898
284,0.144318,0.127886,0.118653,0.108166,0.307479,0.154294,0.294728
285,0.525041,0.276252,0.292960,0.426288,0.448942,0.325009,0.269596
286,0.752933,0.346927,0.464475,0.677083,0.553737,0.535409,0.291941

,69870,43515,531097+543452+49696+51597+542904+544000,542928+544024+531125+543476+49700,97726,69832,43520
0,1.000000,0.655983,0.958974,0.637362,0.549975,0.588123,0.287572
1,0.831494,0.648454,0.863688,0.854802,0.811755,0.651341,0.547426
2,0.950346,1.000000,0.675033,0.853463,1.000000,1.000000,1.000000
3,0.716938,0.628243,0.740523,0.387842,0.664922,0.779693,0.685585
4,0.903021,0.887064,1.000000,1.000000,0.622183,0.473180,0.435260
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

        69870     43515  542928+544024+531125+543476+49700     97726     69832
0    0.146543  0.217240                           0.151274  0.138068  0.184701
1    0.192359  0.275025                           0.260767  0.177295  0.235717
2    0.229543  0.329389                           0.251763  0.199668  0.335751
3    0.204149  0.327821                           0.217936  0.222185  0.280821
4    0.246384  0.383460                           0.275276  0.251662  0.320041
..        ...       ...                                ...       ...       ...
282  0.396241  0.196025                           0.328691  0.351186  0.261717
283  0.213319  0.144235                           0.136112  0.325994  0.176189
284  0.144318  0.127886                           0.108166  0.307479  0.154294
285  0.525041  0.276252                           0.426288  0.448942  0.325009
286  0.752933  0.346927                           0.677083  0.553737  0.535409

[287 rows x 5 columns]

      69870     43515  542928+544024+531125+543476+49700     97726     69832
0  1.000000  0.655983                           0.637362  0.549975  0.588123
1  0.831494  0.648454                           0.854802  0.811755  0.651341
2  0.950346  1.000000                           0.853463  1.000000  1.000000
3  0.716938  0.628243                           0.387842  0.664922  0.779693
4  0.903021  0.887064                           1.000000  0.622183  0.473180
5  0.000000  0.000000                           0.000000  0.000000  0.000000

### Then the normalized data split into <font color="blue">X_train and X_test (from test set)</font>, and
### <font color="blue">y_test (from test set data)</font>

In [24]:
# use the whole dataset for training
Xs_train = norm_Xs_df
# use test set for testing
Xs_test = norm_Xs_test_df

In [25]:
display(Xs_train[0])

,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,...,547018,22788,10511218,528444,38498,19671,45145,98000,8852112,10952
0,0.146543,0.002631,0.103248,0.032468,0.217240,0.196029,0.008188,0.947034,0.189361,0.110844,...,0.385079,0.553093,0.867403,0.293307,0.042300,0.000000,0.010758,0.000000,0.168919,0.494452
1,0.192359,0.005075,0.167035,0.038961,0.275025,0.202623,0.018371,0.989407,0.240414,0.052021,...,0.358278,0.549785,0.867403,0.303150,0.053815,0.004284,0.000000,0.048649,0.182432,0.528378
2,0.229543,0.001534,0.208792,0.032468,0.329389,0.212014,0.052861,1.000000,0.286203,0.109244,...,0.331593,0.616275,0.867403,0.332677,0.058212,0.002203,0.003265,0.093694,0.189189,0.558339
3,0.204149,0.002687,0.208792,0.028139,0.327821,0.252649,0.084580,1.000000,0.249148,0.098439,...,0.304792,0.595766,0.861878,0.200787,0.046043,0.001224,0.006878,0.109910,0.189189,0.604079
4,0.246384,0.004656,0.204408,0.021645,0.383460,0.250084,0.084580,1.000000,0.323855,0.177671,...,0.251305,0.612306,0.861878,0.356299,0.059416,0.012240,0.017205,0.174775,0.209459,0.679120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,0.396241,0.992517,0.789137,0.803030,0.196025,0.260649,0.578415,0.830508,0.255367,0.892577,...,0.243648,0.102547,0.187845,0.460630,0.609150,0.575887,0.362492,0.395495,0.243243,0.868418
283,0.213319,0.995682,0.680511,0.829004,0.144235,0.333870,0.580064,0.872881,0.149130,0.865249,...,0.185636,0.101042,0.337017,0.478346,0.609799,0.507956,0.362707,0.550901,0.304054,0.903305
284,0.144318,0.997745,0.677316,0.829004,0.127886,0.341831,0.590491,0.872881,0.118653,0.852475,...,0.174034,0.085544,0.408840,0.562992,0.612922,0.497674,0.385505,0.589189,0.425676,0.942623
285,0.525041,0.999246,0.677316,0.829004,0.276252,0.425040,0.645930,0.872881,0.292960,0.837681,...,0.150830,0.093715,0.276243,0.633858,0.612922,0.452264,0.396914,0.647748,0.391892,1.000000
286,0.752933,1.000000,0.677316,0.829004,0.346927,0.318424,0.652873,0.872881,0.464475,0.848900,...,0.162432,0.103573,0.127072,0.299213,0.620313,0.427173,0.397092,0.562162,0.297297,0.997298

In [26]:
display(Xs_test[0])

,69870,29845,69839+542292+542548+542544,4164579,43515,49881,94884,14392,531097+543452+49696+51597+542904+544000,22809,...,547018,22788,10511218,528444,38498,19671,45145,98000,8852112,10952
0,1.000000,0.000000,0.000000,1.000000,0.655983,0.320472,0.000000,1.0,0.958974,0.753115,...,0.571429,0.105467,1.00,1.000000,0.000000,1.000000,0.000000,0.002146,0.424242,1.000000
1,0.831494,0.220500,0.590909,1.000000,0.648454,0.305904,0.083290,1.0,0.863688,0.654578,...,1.000000,0.412402,0.00,0.541284,0.098640,0.844884,0.106678,0.060086,0.000000,0.017766
2,0.950346,0.490713,1.000000,0.868421,1.000000,1.000000,0.415996,1.0,0.675033,0.267500,...,0.000000,0.000000,0.00,0.637615,0.244222,0.658966,0.267854,1.000000,0.545455,0.000000
3,0.716938,0.693388,0.672727,0.157895,0.628243,0.504574,0.475005,1.0,0.740523,0.000000,...,0.000000,0.684181,0.46,0.967890,0.605458,0.477448,0.468031,0.763948,1.000000,0.723609
4,0.903021,0.851082,0.918182,0.157895,0.887064,0.498729,0.615805,1.0,1.000000,0.060023,...,0.142857,0.898495,0.32,0.339450,0.958878,0.301430,0.614128,0.753219,0.666667,0.156300
5,0.000000,1.000000,0.985455,0.000000,0.000000,0.000000,1.000000,0.0,0.000000,1.000000,...,0.000000,1.000000,0.30,0.000000,1.000000,0.000000,1.000000,0.000000,0.030303,0.390342

In [27]:
y_train = y

### <b>(C) <u>Models Training And Predict</u></b>

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [30]:
# use move than 76% accuracy cfg and model from the research
LS_params = {'alpha': 1.0, 'copy_X': True, 'fit_intercept': True,
             'max_iter': 1000, 'positive': False, 'precompute': False,
             'random_state': 42, 'selection': 'cyclic', 'tol': 0.0001, 'warm_start': False}

SVR_tune_params = {'C': 10, 'cache_size': 200, 'degree': 3, 'epsilon': 0.1,
                   'gamma': 'scale', 'kernel': 'linear', 'max_iter': -1, 'shrinking': True}

RG_params = {'alpha': 1.0, 'copy_X': True, 'fit_intercept': True,
             'max_iter': None, 'positive': False, 'random_state': None, 'solver': 'auto', 'tol': 0.0001}

MLP_params = {'activation': 'relu', 'alpha': 0.0001, 'batch_size': 'auto', 'beta_1': 0.9, 'beta_2': 0.999,
              'early_stopping': False, 'epsilon': 1e-08, 'hidden_layer_sizes': (100,), 'learning_rate': 'constant',
              'learning_rate_init': 0.001, 'max_fun': 15000, 'max_iter': 30000, 'momentum': 0.9, 'n_iter_no_change': 10,
              'nesterovs_momentum': True, 'power_t': 0.5, 'random_state': 42, 'shuffle': True, 'solver': 'adam', 'tol': 0.0001,
              'validation_fraction': 0.1, 'verbose': False, 'warm_start': False}

LS_tune_params = {'alpha': 0.046415888336127774, 'copy_X': True, 'fit_intercept': True, 'max_iter': 1000,
                  'positive': False, 'precompute': False, 'selection': 'cyclic', 'tol': 0.001, 'warm_start': False}

RG_tune_params = {'alpha': 0.3593813663804626, 'copy_X': True, 'fit_intercept': True, 'max_iter': 1000, 'positive': False, 'solver': 'auto', 'tol': 0.0001}

models = {
    "Lasso": {
                        "model" : Lasso(**LS_params),                   
                        "acc" : "78.05",
                        "train_data" : Xs_train[7],                                      # index 7, use 0.7 thresold
                        "test_data" : Xs_test[7]
                     },
    "SVR (tuned)": {
                        "model" : SVR(**SVR_tune_params),                   
                        "acc" : "77.77",
                        "train_data" : Xs_train[7],                                      # index 7, use 0.7 thresold
                        "test_data" : Xs_test[7]
                     },
    "Ridge"     : {
                        "model" : Ridge(**RG_params),                   
                        "acc" : "77.05",
                        "train_data" : Xs_train[7],                                      # index 7, use 0.7 thresold
                        "test_data" : Xs_test[7]
                     },
    "MLP"     : {
                        "model" : MLPRegressor(**MLP_params),                   
                        "acc" : "76.81",
                        "train_data" : Xs_train[7],                                      # index 7, use 0.7 thresold
                        "test_data" : Xs_test[7]
                     },
    "Lasso (tuned)"     : {
                        "model" : Lasso(**LS_tune_params),                   
                        "acc" : "76.42",
                        "train_data" : Xs_train[7],                                      # index 7, use 0.7 thresold
                        "test_data" : Xs_test[7]
                     },
    "Ridge (tuned)"     : {
                        "model" : Ridge(**RG_tune_params),                   
                        "acc" : "76.42",
                        "train_data" : Xs_train[7],                                      # index 7, use 0.7 thresold
                        "test_data" : Xs_test[7]
                     },
}

In [31]:
date = ["20231101", "20240101", "20240301", "20240501", "20240701", "20240901"]
model_predict_table_md = "|model|Accuracy(%)|" + "|".join(date) + "\n"
model_predict_table_md += "|-|-|-|-|-|-|-|-|\n"

result_date_matrix = []

# Training by dataset, and testing by testset
for model_name, obj in models.items():
    
    # Train the model
    obj["model"].fit(obj["train_data"], y_train)
    
    # predictions
    y_pred = obj["model"].predict(obj["test_data"])

    result_date_matrix.append(y_pred)
    accuracy = obj["acc"]
    model_predict_table_md += (f"{model_name}|{accuracy}|" + "|".join(map(lambda x : f"{x:.4f}", y_pred)) + "\n")

In [32]:
result_date_matrix = np.vstack(result_date_matrix)
date_average_predict = np.mean(result_date_matrix, axis=0)

model_predict_table_md += "|-|-|-|-|-|-|-|-|\n"
model_predict_table_md += (f"Average|-|" + "|".join(map(lambda x : f"{x:.4f}", date_average_predict)))

In [33]:
import os
def export_csv(df, name):
    subdirectory = './predict_csv'
    # Get the current working directory
    current_directory = os.getcwd()
    export_path = os.path.join(current_directory, subdirectory)
    # Ensure the directory exists, if not, create it
    os.makedirs(export_path, exist_ok=True)
    df.to_csv(f'{export_path}/{name}_{dataset_name}.csv', index=False)

In [34]:
# export to a csv

df = pd.DataFrame({
    'Date': np.array(date),
    dataset_name: date_average_predict
})
export_csv(df, "predict")

In [35]:
display(Markdown(model_predict_table_md))

|model|Accuracy(%)|20231101|20240101|20240301|20240501|20240701|20240901
|-|-|-|-|-|-|-|-|
Lasso|78.05|181.6250|206.1475|258.3782|211.0845|173.2838|78.1525
SVR (tuned)|77.77|200.8586|216.4458|263.3745|198.5238|217.7054|66.7526
Ridge|77.05|204.4903|229.7641|283.2486|211.3063|226.3948|70.6533
MLP|76.81|207.9113|230.0703|280.0239|211.1206|230.1503|66.0015
Lasso (tuned)|76.42|185.7982|229.0418|284.7540|209.4911|211.6953|70.0585
Ridge (tuned)|76.42|193.6867|230.3568|285.7277|209.6616|221.3365|69.9810
|-|-|-|-|-|-|-|-|
Average|-|195.7283|223.6377|275.9178|208.5313|213.4277|70.2666