## <u>Maritime Shipping Industry Data Analysis and Prediction</u>
### Chow Tsz Chun Samuel
### Phuc Thien Bao Nguyen, Peter
<br>

## Phase 3 - Objective(s)
- ### Use separate coding file for 53451, 534546 and 549305 Dataset
- ### Use each dataset full set to training
- ### both the training dataset and test set would perform feature selection
- ### From Phase 2 result, apply the test set unseen data to the best model with feature selection threshold get the predict result

In [2]:
!pip install pandas
!pip install matplotlib
!pip install numpy
!python -m pip install --upgrade pip
!pip install ipywidgets
!pip install xgboost

Requirement already satisfied: pandas in c:\users\demon\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\demon\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\demon\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\demon\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\demon\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\demon\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: matplotlib in c:\users\demon\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.23 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\demon\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\demon\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: numpy in c:\users\demon\anaconda3\lib\site-packages (1.26.4)

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

Requirement already satisfied: ipywidgets in c:\users\demon\anaconda3\lib\site-packages (8.1.2)
Requirement already satisfied: comm>=0.1.3 in c:\users\demon\anaconda3\lib\site-packages (from ipywidgets) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in c:\users\demon\anaconda3\lib\site-packages (from ipywidgets) (8.27.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\demon\anaconda3\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.10 in c:\users\demon\anaconda3\lib\site-packages (from ipywidgets) (4.0.10)
Requirement already satisfied: jupyterlab-widgets~=3.0.10 in c:\users\demon\anaconda3\lib\site-packages (from ipywidgets) (3.0.10)
Requirement already satisfied: decorator in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.15.1)
Requirement already satisfied: stack-data in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6 in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (4.11.0)
Requirement already satisfied: colorama in c:\users\demon\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\demon\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\demon\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.5)
Requirement already satisfied: executing in c:\users\demon\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: asttokens in c:\users\demon\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\demon\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: six in c:\users\demon\anaconda3\lib\site-packages (from asttokens->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)
Requirement already satisfied: xgboost in c:\users\demon\anaconda3\lib\site-packages (2.1.2)
Requirement already satisfied: numpy in c:\users\demon\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\demon\anaconda3\lib\site-packages (from xgboost) (1.13.1)

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Markdown, display

## <font color='green'>This Code works on the (534541) Dataset and testset

In [5]:
dataset_name = '534541'
dataset_name_with_date = f"{dataset_name}_with_date"
dataset_file_name = f"{dataset_name}_shifted.csv"

dataset_test_name = f"{dataset_name}_testset"
dataset_test_with_date = f"{dataset_name}_Test_with_date"
dataset_test_file_name = f"test set/{dataset_name}_test.csv"

In [6]:
dataset = {
    dataset_name_with_date : pd.read_csv(dataset_file_name),
    dataset_test_with_date : pd.read_csv(dataset_test_file_name)
}

In [7]:
df_group = {
    dataset_name : dataset[dataset_name_with_date].drop(['date'], axis=1),
    dataset_test_name : dataset[dataset_test_with_date].drop(['date'], axis=1)
}

In [8]:
df_group[dataset_name]

,534541,47027,30213,59288,14392,19597,45086,12437,540732,46204,...,548450,19671,22807,548454,546255,22828,547449,10509791,545629,10952
0,19071.06000,12.730000,267.48089,38.741176,5.6875,25.40350,11289652,1.67583,14.27507,2820468,...,129748.8300,111.50,1786.0,272149.9400,699.47,439.0,104.67000,16.48,13.08,8.00623
1,22223.94000,12.730000,268.98981,39.264706,5.9375,27.63300,12156890,1.70175,14.25326,1330213,...,122607.6100,113.25,1750.0,261656.6100,699.47,431.0,100.72000,16.17,14.66,8.20910
2,23177.78000,13.500000,269.42904,39.264706,6.0000,27.59560,11801976,1.71406,14.28514,2554922,...,130197.7100,112.40,1895.0,277396.6000,699.47,434.0,100.72000,15.86,11.27,8.38826
3,20849.68000,13.500000,270.42378,39.264706,6.0000,22.84500,11984532,1.70810,14.28443,1712977,...,125894.4600,112.00,1792.0,270838.2700,698.78,445.0,99.14000,15.47,12.86,8.66177
4,20029.62000,12.470000,271.39603,39.788235,6.0000,27.33750,11477215,1.72843,14.32377,1055913,...,133052.8800,116.50,1679.0,278708.2700,698.78,476.0,99.14000,15.49,11.43,9.11050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,16168.10000,21.477273,982.28829,61.750000,4.2500,83.28222,22027906,1.33008,11.70630,3823384,...,155891.7143,377.25,7070.0,195312.7143,1011.00,4062.0,91.54163,13.85,38.44,10.48568
280,13682.27273,20.454545,985.20054,63.000000,4.4375,75.69478,20403118,1.33957,11.73972,4753750,...,172491.4286,367.75,7093.0,203099.1429,992.00,4252.0,89.50135,12.00,35.73,10.82323
281,12900.00000,18.409091,987.60788,63.500000,4.7000,74.97864,20267384,1.34540,11.77609,6995849,...,178820.4286,343.00,6882.0,198758.8571,1000.00,4136.0,89.17437,10.37,29.60,10.78208
282,12136.81818,18.920455,990.18845,63.500000,5.0000,80.16000,21505070,1.33302,11.80680,3366989,...,191656.0000,346.75,6903.0,204858.0000,994.00,4128.0,89.53052,10.09,29.14,10.24245
283,12714.90476,19.943182,992.30882,64.000000,5.2500,85.10435,21379290,1.35027,11.84248,2433726,...,190635.7143,319.00,7312.0,202044.4286,981.00,4162.0,86.10594,12.26,29.66,10.45107

In [9]:
df_group[dataset_test_name]

,534541,47027,30213,59288,14392,19597,45086,12437,540732,46204,...,548450,19671,22807,548454,546255,22828,547449,10509791,545629,10952
0,19655.04546,21.477273,996.97957,64.50,5.25,88.70409,22035815,1.36987,11.90778,4230850,...,165986.2857,296.25,7454,205839.7143,937,4358,94.13249,10.78,31.39,11.02928
1,26580.00000,20.965909,1002.15845,67.00,5.25,77.23211,22632853,1.32990,11.99014,7493700,...,147746.8571,289.20,7524,205078.2857,902,4551,91.14156,3.21,34.22,10.53502
2,19953.00000,25.500000,1007.87876,67.75,5.25,81.71619,25072273,1.34302,12.08208,2870490,...,137788.0000,280.75,7025,187127.0000,944,4274,87.15412,2.98,28.09,10.52608
3,21222.38095,29.500000,1011.95156,70.50,5.25,88.81727,25785866,1.35595,12.15622,4682500,...,154951.0000,272.50,7119,207337.8571,995,4438,87.46722,4.18,25.76,10.89020
4,25397.45000,29.000000,1016.99085,76.50,5.25,82.92800,26931647,1.35245,12.22597,7187463,...,180769.5714,264.50,7239,207601.4286,1024,4329,89.98818,5.57,23.77,10.60473
5,22878.57143,29.000000,1022.79867,76.50,5.00,78.87500,29902696,1.31940,12.30373,4114400,...,192930.7143,250.80,7544,213155.7143,993,4437,91.54315,8.91,24.79,10.72250

## (B) Data Wrangling
<br>

### <b>(B1) <u>Data validation</u></b>
### The very first step after extraction is verifying the data on checking if included invalid value
### The dataset is clear without any NULL value

In [11]:
df_group[dataset_name].isnull().sum()

534541      0
47027       0
30213       0
59288       0
14392       0
19597       0
45086       0
12437       0
540732      0
46204       0
534435      0
10722376    0
541454      0
22788       0
548430      0
22555       0
11279191    0
22539       0
38498       0
22768       0
548450      0
19671       0
22807       0
548454      0
546255      0
22828       0
547449      0
10509791    0
545629      0
10952       0
dtype: int64

In [12]:
df_group[dataset_test_name].isnull().sum()

534541      0
47027       0
30213       0
59288       0
14392       0
19597       0
45086       0
12437       0
540732      0
46204       0
534435      0
10722376    0
541454      0
22788       0
548430      0
22555       0
11279191    0
22539       0
38498       0
22768       0
548450      0
19671       0
22807       0
548454      0
546255      0
22828       0
547449      0
10509791    0
545629      0
10952       0
dtype: int64

In [13]:
correlation = df_group[dataset_name].corr().round(2)

target = "534541"
thresholds = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
features_group_size = len(thresholds)

df_featureSelected = []
df_featureSelected_testset = []

target_correlation = correlation[target]

for i in range(features_group_size):
    features_above_threshold = target_correlation[abs(target_correlation) >= thresholds[i]].index.tolist()

    # Remove the target itself from the list
    features_above_threshold.remove(target)

    df_featureSelected.append(df_group[dataset_name].filter(items=features_above_threshold))
    df_featureSelected_testset.append(df_group[dataset_test_name].filter(items=features_above_threshold))

    display(df_featureSelected[-1])
    display(df_featureSelected_testset[-1])

,47027,30213,59288,14392,19597,45086,12437,540732,46204,534435,...,548450,19671,22807,548454,546255,22828,547449,10509791,545629,10952
0,12.730000,267.48089,38.741176,5.6875,25.40350,11289652,1.67583,14.27507,2820468,1.134,...,129748.8300,111.50,1786.0,272149.9400,699.47,439.0,104.67000,16.48,13.08,8.00623
1,12.730000,268.98981,39.264706,5.9375,27.63300,12156890,1.70175,14.25326,1330213,1.444,...,122607.6100,113.25,1750.0,261656.6100,699.47,431.0,100.72000,16.17,14.66,8.20910
2,13.500000,269.42904,39.264706,6.0000,27.59560,11801976,1.71406,14.28514,2554922,1.612,...,130197.7100,112.40,1895.0,277396.6000,699.47,434.0,100.72000,15.86,11.27,8.38826
3,13.500000,270.42378,39.264706,6.0000,22.84500,11984532,1.70810,14.28443,1712977,1.761,...,125894.4600,112.00,1792.0,270838.2700,698.78,445.0,99.14000,15.47,12.86,8.66177
4,12.470000,271.39603,39.788235,6.0000,27.33750,11477215,1.72843,14.32377,1055913,2.150,...,133052.8800,116.50,1679.0,278708.2700,698.78,476.0,99.14000,15.49,11.43,9.11050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,21.477273,982.28829,61.750000,4.2500,83.28222,22027906,1.33008,11.70630,3823384,2.941,...,155891.7143,377.25,7070.0,195312.7143,1011.00,4062.0,91.54163,13.85,38.44,10.48568
280,20.454545,985.20054,63.000000,4.4375,75.69478,20403118,1.33957,11.73972,4753750,3.030,...,172491.4286,367.75,7093.0,203099.1429,992.00,4252.0,89.50135,12.00,35.73,10.82323
281,18.409091,987.60788,63.500000,4.7000,74.97864,20267384,1.34540,11.77609,6995849,3.044,...,178820.4286,343.00,6882.0,198758.8571,1000.00,4136.0,89.17437,10.37,29.60,10.78208
282,18.920455,990.18845,63.500000,5.0000,80.16000,21505070,1.33302,11.80680,3366989,3.068,...,191656.0000,346.75,6903.0,204858.0000,994.00,4128.0,89.53052,10.09,29.14,10.24245
283,19.943182,992.30882,64.000000,5.2500,85.10435,21379290,1.35027,11.84248,2433726,3.033,...,190635.7143,319.00,7312.0,202044.4286,981.00,4162.0,86.10594,12.26,29.66,10.45107

,47027,30213,59288,14392,19597,45086,12437,540732,46204,534435,...,548450,19671,22807,548454,546255,22828,547449,10509791,545629,10952
0,21.477273,996.97957,64.50,5.25,88.70409,22035815,1.36987,11.90778,4230850,3.014,...,165986.2857,296.25,7454,205839.7143,937,4358,94.13249,10.78,31.39,11.02928
1,20.965909,1002.15845,67.00,5.25,77.23211,22632853,1.32990,11.99014,7493700,3.010,...,147746.8571,289.20,7524,205078.2857,902,4551,91.14156,3.21,34.22,10.53502
2,25.500000,1007.87876,67.75,5.25,81.71619,25072273,1.34302,12.08208,2870490,3.122,...,137788.0000,280.75,7025,187127.0000,944,4274,87.15412,2.98,28.09,10.52608
3,29.500000,1011.95156,70.50,5.25,88.81727,25785866,1.35595,12.15622,4682500,3.008,...,154951.0000,272.50,7119,207337.8571,995,4438,87.46722,4.18,25.76,10.89020
4,29.000000,1016.99085,76.50,5.25,82.92800,26931647,1.35245,12.22597,7187463,2.961,...,180769.5714,264.50,7239,207601.4286,1024,4329,89.98818,5.57,23.77,10.60473
5,29.000000,1022.79867,76.50,5.00,78.87500,29902696,1.31940,12.30373,4114400,3.059,...,192930.7143,250.80,7544,213155.7143,993,4437,91.54315,8.91,24.79,10.72250

,47027,30213,59288,14392,45086,12437,540732,46204,10722376,541454,...,22768,548450,22807,548454,546255,22828,547449,10509791,545629,10952
0,12.730000,267.48089,38.741176,5.6875,11289652,1.67583,14.27507,2820468,15.74,4.5600,...,961.000,129748.8300,1786.0,272149.9400,699.47,439.0,104.67000,16.48,13.08,8.00623
1,12.730000,268.98981,39.264706,5.9375,12156890,1.70175,14.25326,1330213,15.75,4.5600,...,950.000,122607.6100,1750.0,261656.6100,699.47,431.0,100.72000,16.17,14.66,8.20910
2,13.500000,269.42904,39.264706,6.0000,11801976,1.71406,14.28514,2554922,15.78,4.5600,...,1020.000,130197.7100,1895.0,277396.6000,699.47,434.0,100.72000,15.86,11.27,8.38826
3,13.500000,270.42378,39.264706,6.0000,11984532,1.70810,14.28443,1712977,15.77,4.5600,...,958.000,125894.4600,1792.0,270838.2700,698.78,445.0,99.14000,15.47,12.86,8.66177
4,12.470000,271.39603,39.788235,6.0000,11477215,1.72843,14.32377,1055913,15.77,4.6000,...,915.000,133052.8800,1679.0,278708.2700,698.78,476.0,99.14000,15.49,11.43,9.11050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,21.477273,982.28829,61.750000,4.2500,22027906,1.33008,11.70630,3823384,15.87,11.8875,...,258.216,155891.7143,7070.0,195312.7143,1011.00,4062.0,91.54163,13.85,38.44,10.48568
280,20.454545,985.20054,63.000000,4.4375,20403118,1.33957,11.73972,4753750,18.00,10.2000,...,310.039,172491.4286,7093.0,203099.1429,992.00,4252.0,89.50135,12.00,35.73,10.82323
281,18.409091,987.60788,63.500000,4.7000,20267384,1.34540,11.77609,6995849,16.55,11.1000,...,326.824,178820.4286,6882.0,198758.8571,1000.00,4136.0,89.17437,10.37,29.60,10.78208
282,18.920455,990.18845,63.500000,5.0000,21505070,1.33302,11.80680,3366989,17.93,11.1500,...,312.935,191656.0000,6903.0,204858.0000,994.00,4128.0,89.53052,10.09,29.14,10.24245
283,19.943182,992.30882,64.000000,5.2500,21379290,1.35027,11.84248,2433726,16.66,11.8500,...,217.000,190635.7143,7312.0,202044.4286,981.00,4162.0,86.10594,12.26,29.66,10.45107

,47027,30213,59288,14392,45086,12437,540732,46204,10722376,541454,...,22768,548450,22807,548454,546255,22828,547449,10509791,545629,10952
0,21.477273,996.97957,64.50,5.25,22035815,1.36987,11.90778,4230850,17.52,16.00955,...,265,165986.2857,7454,205839.7143,937,4358,94.13249,10.78,31.39,11.02928
1,20.965909,1002.15845,67.00,5.25,22632853,1.32990,11.99014,7493700,18.06,14.46979,...,220,147746.8571,7524,205078.2857,902,4551,91.14156,3.21,34.22,10.53502
2,25.500000,1007.87876,67.75,5.25,25072273,1.34302,12.08208,2870490,16.23,9.00150,...,185,137788.0000,7025,187127.0000,944,4274,87.15412,2.98,28.09,10.52608
3,29.500000,1011.95156,70.50,5.25,25785866,1.35595,12.15622,4682500,19.08,9.96323,...,215,154951.0000,7119,207337.8571,995,4438,87.46722,4.18,25.76,10.89020
4,29.000000,1016.99085,76.50,5.25,26931647,1.35245,12.22597,7187463,16.89,12.26033,...,210,180769.5714,7239,207601.4286,1024,4329,89.98818,5.57,23.77,10.60473
5,29.000000,1022.79867,76.50,5.00,29902696,1.31940,12.30373,4114400,18.68,13.14891,...,200,192930.7143,7544,213155.7143,993,4437,91.54315,8.91,24.79,10.72250

,47027,30213,59288,14392,45086,12437,540732,46204,10722376,22788,22555,22539,38498,22768,22807,548454,547449,10509791,545629,10952
0,12.730000,267.48089,38.741176,5.6875,11289652,1.67583,14.27507,2820468,15.74,1900.00,4448.84807,100.00000,103.45742,961.000,1786.0,272149.9400,104.67000,16.48,13.08,8.00623
1,12.730000,268.98981,39.264706,5.9375,12156890,1.70175,14.25326,1330213,15.75,1890.00,4468.03983,97.35228,105.10912,950.000,1750.0,261656.6100,100.72000,16.17,14.66,8.20910
2,13.500000,269.42904,39.264706,6.0000,11801976,1.71406,14.28514,2554922,15.78,2091.00,4484.25294,95.25874,105.73986,1020.000,1895.0,277396.6000,100.72000,15.86,11.27,8.38826
3,13.500000,270.42378,39.264706,6.0000,11984532,1.70810,14.28443,1712977,15.77,2029.00,4506.54207,92.77604,103.99441,958.000,1792.0,270838.2700,99.14000,15.47,12.86,8.66177
4,12.470000,271.39603,39.788235,6.0000,11477215,1.72843,14.32377,1055913,15.77,2079.00,4575.66570,88.58156,105.91260,915.000,1679.0,278708.2700,99.14000,15.49,11.43,9.11050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,21.477273,982.28829,61.750000,4.2500,22027906,1.33008,11.70630,3823384,15.87,544.30,4303.49538,108.25842,180.86651,258.216,7070.0,195312.7143,91.54163,13.85,38.44,10.48568
280,20.454545,985.20054,63.000000,4.4375,20403118,1.33957,11.73972,4753750,18.00,603.40,4313.11221,106.98998,183.92033,310.039,7093.0,203099.1429,89.50135,12.00,35.73,10.82323
281,18.409091,987.60788,63.500000,4.7000,20267384,1.34540,11.77609,6995849,16.55,485.70,4354.64268,107.00623,184.35019,326.824,6882.0,198758.8571,89.17437,10.37,29.60,10.78208
282,18.920455,990.18845,63.500000,5.0000,21505070,1.33302,11.80680,3366989,17.93,538.00,4383.62290,108.88648,184.76796,312.935,6903.0,204858.0000,89.53052,10.09,29.14,10.24245
283,19.943182,992.30882,64.000000,5.2500,21379290,1.35027,11.84248,2433726,16.66,533.45,4388.76151,107.43579,184.86106,217.000,7312.0,202044.4286,86.10594,12.26,29.66,10.45107

,47027,30213,59288,14392,45086,12437,540732,46204,10722376,22788,22555,22539,38498,22768,22807,548454,547449,10509791,545629,10952
0,21.477273,996.97957,64.50,5.25,22035815,1.36987,11.90778,4230850,17.52,511.300,4393.84972,103.95064,185.30908,265,7454,205839.7143,94.13249,10.78,31.39,11.02928
1,20.965909,1002.15845,67.00,5.25,22632853,1.32990,11.99014,7493700,18.06,556.700,4362.91726,107.79636,186.64852,220,7524,205078.2857,91.14156,3.21,34.22,10.53502
2,25.500000,1007.87876,67.75,5.25,25072273,1.34302,12.08208,2870490,16.23,495.700,4349.81186,106.47767,188.62539,185,7025,187127.0000,87.15412,2.98,28.09,10.52608
3,29.500000,1011.95156,70.50,5.25,25785866,1.35595,12.15622,4682500,19.08,596.900,4358.84781,105.72153,193.53065,215,7119,207337.8571,87.46722,4.18,25.76,10.89020
4,29.000000,1016.99085,76.50,5.25,26931647,1.35245,12.22597,7187463,16.89,628.600,4361.97998,105.96044,198.32977,210,7239,207601.4286,89.98818,5.57,23.77,10.60473
5,29.000000,1022.79867,76.50,5.00,29902696,1.31940,12.30373,4114400,18.68,643.614,4284.69473,108.11359,198.88817,200,7544,213155.7143,91.54315,8.91,24.79,10.72250

,47027,30213,59288,14392,540732,46204,10722376,22788,22555,22539,38498,22768,22807,548454,10509791,545629,10952
0,12.730000,267.48089,38.741176,5.6875,14.27507,2820468,15.74,1900.00,4448.84807,100.00000,103.45742,961.000,1786.0,272149.9400,16.48,13.08,8.00623
1,12.730000,268.98981,39.264706,5.9375,14.25326,1330213,15.75,1890.00,4468.03983,97.35228,105.10912,950.000,1750.0,261656.6100,16.17,14.66,8.20910
2,13.500000,269.42904,39.264706,6.0000,14.28514,2554922,15.78,2091.00,4484.25294,95.25874,105.73986,1020.000,1895.0,277396.6000,15.86,11.27,8.38826
3,13.500000,270.42378,39.264706,6.0000,14.28443,1712977,15.77,2029.00,4506.54207,92.77604,103.99441,958.000,1792.0,270838.2700,15.47,12.86,8.66177
4,12.470000,271.39603,39.788235,6.0000,14.32377,1055913,15.77,2079.00,4575.66570,88.58156,105.91260,915.000,1679.0,278708.2700,15.49,11.43,9.11050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,21.477273,982.28829,61.750000,4.2500,11.70630,3823384,15.87,544.30,4303.49538,108.25842,180.86651,258.216,7070.0,195312.7143,13.85,38.44,10.48568
280,20.454545,985.20054,63.000000,4.4375,11.73972,4753750,18.00,603.40,4313.11221,106.98998,183.92033,310.039,7093.0,203099.1429,12.00,35.73,10.82323
281,18.409091,987.60788,63.500000,4.7000,11.77609,6995849,16.55,485.70,4354.64268,107.00623,184.35019,326.824,6882.0,198758.8571,10.37,29.60,10.78208
282,18.920455,990.18845,63.500000,5.0000,11.80680,3366989,17.93,538.00,4383.62290,108.88648,184.76796,312.935,6903.0,204858.0000,10.09,29.14,10.24245
283,19.943182,992.30882,64.000000,5.2500,11.84248,2433726,16.66,533.45,4388.76151,107.43579,184.86106,217.000,7312.0,202044.4286,12.26,29.66,10.45107

,47027,30213,59288,14392,540732,46204,10722376,22788,22555,22539,38498,22768,22807,548454,10509791,545629,10952
0,21.477273,996.97957,64.50,5.25,11.90778,4230850,17.52,511.300,4393.84972,103.95064,185.30908,265,7454,205839.7143,10.78,31.39,11.02928
1,20.965909,1002.15845,67.00,5.25,11.99014,7493700,18.06,556.700,4362.91726,107.79636,186.64852,220,7524,205078.2857,3.21,34.22,10.53502
2,25.500000,1007.87876,67.75,5.25,12.08208,2870490,16.23,495.700,4349.81186,106.47767,188.62539,185,7025,187127.0000,2.98,28.09,10.52608
3,29.500000,1011.95156,70.50,5.25,12.15622,4682500,19.08,596.900,4358.84781,105.72153,193.53065,215,7119,207337.8571,4.18,25.76,10.89020
4,29.000000,1016.99085,76.50,5.25,12.22597,7187463,16.89,628.600,4361.97998,105.96044,198.32977,210,7239,207601.4286,5.57,23.77,10.60473
5,29.000000,1022.79867,76.50,5.00,12.30373,4114400,18.68,643.614,4284.69473,108.11359,198.88817,200,7544,213155.7143,8.91,24.79,10.72250

,47027,30213,59288,14392,540732,46204,22788,22539,38498,22768,22807,548454,10509791,10952
0,12.730000,267.48089,38.741176,5.6875,14.27507,2820468,1900.00,100.00000,103.45742,961.000,1786.0,272149.9400,16.48,8.00623
1,12.730000,268.98981,39.264706,5.9375,14.25326,1330213,1890.00,97.35228,105.10912,950.000,1750.0,261656.6100,16.17,8.20910
2,13.500000,269.42904,39.264706,6.0000,14.28514,2554922,2091.00,95.25874,105.73986,1020.000,1895.0,277396.6000,15.86,8.38826
3,13.500000,270.42378,39.264706,6.0000,14.28443,1712977,2029.00,92.77604,103.99441,958.000,1792.0,270838.2700,15.47,8.66177
4,12.470000,271.39603,39.788235,6.0000,14.32377,1055913,2079.00,88.58156,105.91260,915.000,1679.0,278708.2700,15.49,9.11050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,21.477273,982.28829,61.750000,4.2500,11.70630,3823384,544.30,108.25842,180.86651,258.216,7070.0,195312.7143,13.85,10.48568
280,20.454545,985.20054,63.000000,4.4375,11.73972,4753750,603.40,106.98998,183.92033,310.039,7093.0,203099.1429,12.00,10.82323
281,18.409091,987.60788,63.500000,4.7000,11.77609,6995849,485.70,107.00623,184.35019,326.824,6882.0,198758.8571,10.37,10.78208
282,18.920455,990.18845,63.500000,5.0000,11.80680,3366989,538.00,108.88648,184.76796,312.935,6903.0,204858.0000,10.09,10.24245
283,19.943182,992.30882,64.000000,5.2500,11.84248,2433726,533.45,107.43579,184.86106,217.000,7312.0,202044.4286,12.26,10.45107

,47027,30213,59288,14392,540732,46204,22788,22539,38498,22768,22807,548454,10509791,10952
0,21.477273,996.97957,64.50,5.25,11.90778,4230850,511.300,103.95064,185.30908,265,7454,205839.7143,10.78,11.02928
1,20.965909,1002.15845,67.00,5.25,11.99014,7493700,556.700,107.79636,186.64852,220,7524,205078.2857,3.21,10.53502
2,25.500000,1007.87876,67.75,5.25,12.08208,2870490,495.700,106.47767,188.62539,185,7025,187127.0000,2.98,10.52608
3,29.500000,1011.95156,70.50,5.25,12.15622,4682500,596.900,105.72153,193.53065,215,7119,207337.8571,4.18,10.89020
4,29.000000,1016.99085,76.50,5.25,12.22597,7187463,628.600,105.96044,198.32977,210,7239,207601.4286,5.57,10.60473
5,29.000000,1022.79867,76.50,5.00,12.30373,4114400,643.614,108.11359,198.88817,200,7544,213155.7143,8.91,10.72250

,47027,59288,14392,540732,46204,22788,38498,548454,10509791
0,12.730000,38.741176,5.6875,14.27507,2820468,1900.00,103.45742,272149.9400,16.48
1,12.730000,39.264706,5.9375,14.25326,1330213,1890.00,105.10912,261656.6100,16.17
2,13.500000,39.264706,6.0000,14.28514,2554922,2091.00,105.73986,277396.6000,15.86
3,13.500000,39.264706,6.0000,14.28443,1712977,2029.00,103.99441,270838.2700,15.47
4,12.470000,39.788235,6.0000,14.32377,1055913,2079.00,105.91260,278708.2700,15.49
...,...,...,...,...,...,...,...,...,...
279,21.477273,61.750000,4.2500,11.70630,3823384,544.30,180.86651,195312.7143,13.85
280,20.454545,63.000000,4.4375,11.73972,4753750,603.40,183.92033,203099.1429,12.00
281,18.409091,63.500000,4.7000,11.77609,6995849,485.70,184.35019,198758.8571,10.37
282,18.920455,63.500000,5.0000,11.80680,3366989,538.00,184.76796,204858.0000,10.09
283,19.943182,64.000000,5.2500,11.84248,2433726,533.45,184.86106,202044.4286,12.26

,47027,59288,14392,540732,46204,22788,38498,548454,10509791
0,21.477273,64.50,5.25,11.90778,4230850,511.300,185.30908,205839.7143,10.78
1,20.965909,67.00,5.25,11.99014,7493700,556.700,186.64852,205078.2857,3.21
2,25.500000,67.75,5.25,12.08208,2870490,495.700,188.62539,187127.0000,2.98
3,29.500000,70.50,5.25,12.15622,4682500,596.900,193.53065,207337.8571,4.18
4,29.000000,76.50,5.25,12.22597,7187463,628.600,198.32977,207601.4286,5.57
5,29.000000,76.50,5.00,12.30373,4114400,643.614,198.88817,213155.7143,8.91

         47027      59288  10509791
0    12.730000  38.741176     16.48
1    12.730000  39.264706     16.17
2    13.500000  39.264706     15.86
3    13.500000  39.264706     15.47
4    12.470000  39.788235     15.49
..         ...        ...       ...
279  21.477273  61.750000     13.85
280  20.454545  63.000000     12.00
281  18.409091  63.500000     10.37
282  18.920455  63.500000     10.09
283  19.943182  64.000000     12.26

[284 rows x 3 columns]

       47027  59288  10509791
0  21.477273  64.50     10.78
1  20.965909  67.00      3.21
2  25.500000  67.75      2.98
3  29.500000  70.50      4.18
4  29.000000  76.50      5.57
5  29.000000  76.50      8.91

         47027      59288
0    12.730000  38.741176
1    12.730000  39.264706
2    13.500000  39.264706
3    13.500000  39.264706
4    12.470000  39.788235
..         ...        ...
279  21.477273  61.750000
280  20.454545  63.000000
281  18.409091  63.500000
282  18.920455  63.500000
283  19.943182  64.000000

[284 rows x 2 columns]

       47027  59288
0  21.477273  64.50
1  20.965909  67.00
2  25.500000  67.75
3  29.500000  70.50
4  29.000000  76.50
5  29.000000  76.50

         47027
0    12.730000
1    12.730000
2    13.500000
3    13.500000
4    12.470000
..         ...
279  21.477273
280  20.454545
281  18.409091
282  18.920455
283  19.943182

[284 rows x 1 columns]

       47027
0  21.477273
1  20.965909
2  25.500000
3  29.500000
4  29.000000
5  29.000000

### <b>(B2) <u>Split X Features and y result</u></b>

In [15]:
# A list of different features selected input
Xs = df_featureSelected #df_group[dataset_name].iloc[:, 1:]
Xs_test = df_featureSelected_testset
print(type(Xs[0]))

<class 'pandas.core.frame.DataFrame'>

In [16]:
y = df_group[dataset_name].iloc[:, 0]
y

0      19071.06000
1      22223.94000
2      23177.78000
3      20849.68000
4      20029.62000
          ...
279    16168.10000
280    13682.27273
281    12900.00000
282    12136.81818
283    12714.90476
Name: 534541, Length: 284, dtype: float64

In [17]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\demon\anaconda3\lib\site-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\demon\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\demon\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\demon\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\demon\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

### <b>(B3) <u>Data Normalization</u></b>
#### Since the X Features data ranging from single digit to $10^5$ scale, it is essential to perform <font color="blue">Normalization</font>
<br>

### <font color="blue">Max Min Normalization</font> is chosen

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
bApplyNormalization = 1

norm_Xs = [df.copy() for df in Xs]
norm_Xs_test = [df.copy() for df in Xs_test]
print(type(Xs[0]))

if bApplyNormalization:
    for i in range(features_group_size):
        scalerMaxMin = MinMaxScaler(feature_range=(0, 1))
        scalerMaxMin_test = MinMaxScaler(feature_range=(0, 1))
        norm_Xs[i] = scalerMaxMin.fit_transform(Xs[i])
        norm_Xs_test[i] = scalerMaxMin_test.fit_transform(Xs_test[i])

<class 'pandas.core.frame.DataFrame'>

In [21]:
norm_Xs

[array([[0.05134015, 0.        , 0.04761905, ..., 0.78347407, 0.12491373,
         0.51209796],
        [0.05134015, 0.00208176, 0.05555556, ..., 0.76477684, 0.17943409,
         0.54723488],
        [0.05877342, 0.00268774, 0.05555556, ..., 0.74607961, 0.06245687,
         0.57826524],
        ...,
        [0.10616385, 0.99351441, 0.42295345, ..., 0.41495778, 0.69496204,
         0.99287285],
        [0.11110036, 0.99707466, 0.42295345, ..., 0.39806996, 0.67908903,
         0.89940939],
        [0.12097336, 1.        , 0.43053326, ..., 0.52895054, 0.69703244,
         0.9355422 ]]),
 array([[0.05134015, 0.        , 0.04761905, ..., 0.78347407, 0.12491373,
         0.51209796],
        [0.05134015, 0.00208176, 0.05555556, ..., 0.76477684, 0.17943409,
         0.54723488],
        [0.05877342, 0.00268774, 0.05555556, ..., 0.74607961, 0.06245687,
         0.57826524],
        ...,
        [0.10616385, 0.99351441, 0.42295345, ..., 0.41495778, 0.69496204,
         0.99287285],
        [0.11110036, 0.99707466, 0.42295345, ..., 0.39806996, 0.67908903,
         0.89940939],
        [0.12097336, 1.        , 0.43053326, ..., 0.52895054, 0.69703244,
         0.9355422 ]]),
 array([[0.05134015, 0.        , 0.04761905, ..., 0.78347407, 0.12491373,
         0.51209796],
        [0.05134015, 0.00208176, 0.05555556, ..., 0.76477684, 0.17943409,
         0.54723488],
        [0.05877342, 0.00268774, 0.05555556, ..., 0.74607961, 0.06245687,
         0.57826524],
        ...,
        [0.10616385, 0.99351441, 0.42295345, ..., 0.41495778, 0.69496204,
         0.99287285],
        [0.11110036, 0.99707466, 0.42295345, ..., 0.39806996, 0.67908903,
         0.89940939],
        [0.12097336, 1.        , 0.43053326, ..., 0.52895054, 0.69703244,
         0.9355422 ]]),
 array([[0.05134015, 0.        , 0.04761905, ..., 0.78347407, 0.12491373,
         0.51209796],
        [0.05134015, 0.00208176, 0.05555556, ..., 0.76477684, 0.17943409,
         0.54723488],
        [0.05877342, 0.00268774, 0.05555556, ..., 0.74607961, 0.06245687,
         0.57826524],
        ...,
        [0.10616385, 0.99351441, 0.42295345, ..., 0.41495778, 0.69496204,
         0.99287285],
        [0.11110036, 0.99707466, 0.42295345, ..., 0.39806996, 0.67908903,
         0.89940939],
        [0.12097336, 1.        , 0.43053326, ..., 0.52895054, 0.69703244,
         0.9355422 ]]),
 array([[0.05134015, 0.        , 0.04761905, ..., 0.6791905 , 0.78347407,
         0.51209796],
        [0.05134015, 0.00208176, 0.05555556, ..., 0.62786097, 0.76477684,
         0.54723488],
        [0.05877342, 0.00268774, 0.05555556, ..., 0.70485524, 0.74607961,
         0.57826524],
        ...,
        [0.10616385, 0.99351441, 0.42295345, ..., 0.32018819, 0.41495778,
         0.99287285],
        [0.11110036, 0.99707466, 0.42295345, ..., 0.35002296, 0.39806996,
         0.89940939],
        [0.12097336, 1.        , 0.43053326, ..., 0.33626   , 0.52895054,
         0.9355422 ]]),
 array([[0.05134015, 0.04761905, 0.9470339 , ..., 0.04229988, 0.6791905 ,
         0.78347407],
        [0.05134015, 0.05555556, 0.98940678, ..., 0.05381458, 0.62786097,
         0.76477684],
        [0.05877342, 0.05555556, 1.        , ..., 0.05821173, 0.70485524,
         0.74607961],
        ...,
        [0.10616385, 0.42295345, 0.77966102, ..., 0.60623763, 0.32018819,
         0.41495778],
        [0.11110036, 0.42295345, 0.83050847, ..., 0.60915008, 0.35002296,
         0.39806996],
        [0.12097336, 0.43053326, 0.87288136, ..., 0.60979912, 0.33626   ,
         0.52895054]]),
 array([[0.05134015, 0.04761905, 0.78347407],
        [0.05134015, 0.05555556, 0.76477684],
        [0.05877342, 0.05555556, 0.74607961],
        [0.05877342, 0.05555556, 0.7225573 ],
        [0.04883021, 0.06349206, 0.72376357],
        [0.04390687, 0.05555556, 0.70084439],
        [0.04390687, 0.07142857, 0.70386007],
        [0.05877342, 0.07936508, 0.67189385],
        [0.06369676, 0.07936508, 0.67551267],
        [0.05877342, 0.0952381 , 0.67852835],
        [0.05877342, 0.1031746 , 0.67671894],
        [0.05877342, 0.1031746 , 0.68033776],
        [0.04883021, 0.0952381 , 0.68335344],
        [0.04883021, 0.0952381 , 0.70566948],
        [0.04883021, 0.11904762, 0.70868516],
        [0.04883021, 0.1031746 , 0.71170084],
        [0.04883021, 0.1031746 , 0.69662244],
        [0.05385009, 0.11111111, 0.69963812],
        [0.04883021, 0.11111111, 0.71833534],
        [0.02904032, 0.03968254, 0.74607961],
        [0.02904032, 0.05555556, 0.74668275],
        [0.02653038, 0.05555556, 0.76537998],
        [0.04429302, 0.04761905, 0.75874548],
        [0.04429302, 0.03174603, 0.79794934],
        [0.04429302, 0.02380952, 0.81182147],
        [0.0471891 , 0.01984127, 0.81182147],
        [0.0471891 , 0.01984127, 0.82509047],
        [0.0471891 , 0.00793651, 0.82509047],
        [0.0471891 , 0.00793651, 0.82509047],
        [0.0471891 , 0.00793651, 0.82509047],
        [0.0471891 , 0.        , 0.83896261],
        [0.0471891 , 0.        , 0.83896261],
        [0.0471891 , 0.01587302, 0.8522316 ],
        [0.04429302, 0.02380952, 0.8522316 ],
        [0.05008518, 0.03174603, 0.8522316 ],
        [0.05587734, 0.03571429, 0.8522316 ],
        [0.06166951, 0.05555556, 0.8455971 ],
        [0.06166951, 0.06349206, 0.8455971 ],
        [0.07325383, 0.07142857, 0.8455971 ],
        [0.07325383, 0.07142857, 0.8455971 ],
        [0.07325383, 0.07142857, 0.8588661 ],
        [0.07325383, 0.07142857, 0.87273824],
        [0.10221465, 0.07936508, 0.87937274],
        [0.10221465, 0.1031746 , 0.89264174],
        [0.11379898, 0.13492063, 0.89264174],
        [0.16013629, 0.15079365, 0.89264174],
        [0.17172061, 0.22222222, 0.87937274],
        [0.18330494, 0.22222222, 0.8455971 ],
        [0.28756388, 0.25396825, 0.8455971 ],
        [0.29914821, 0.25396825, 0.81182147],
        [0.29914821, 0.29365079, 0.78468034],
        [0.28756388, 0.34920635, 0.78468034],
        [0.2528109 , 0.33333333, 0.77141134],
        [0.20068143, 0.34920635, 0.77141134],
        [0.24122658, 0.37301587, 0.77141134],
        [0.27597956, 0.3968254 , 0.70325694],
        [0.29914821, 0.42857143, 0.6761158 ],
        [0.29914821, 0.46031746, 0.60856454],
        [0.33390119, 0.47619048, 0.54101327],
        [0.33390119, 0.47619048, 0.54101327],
        [0.39182283, 0.50793651, 0.54101327],
        [0.41499148, 0.50793651, 0.5814234 ],
        [0.41499148, 0.53968254, 0.5814234 ],
        [0.41499148, 0.53968254, 0.5814234 ],
        [0.39182283, 0.53968254, 0.24366707],
        [0.38255537, 0.44444444, 0.24366707],
        [0.32810903, 0.44444444, 0.27020507],
        [0.30494037, 0.4047619 , 0.27020507],
        [0.30494037, 0.3968254 , 0.27020507],
        [0.30494037, 0.3968254 , 0.27020507],
        [0.30494037, 0.3968254 , 0.27020507],
        [0.2528109 , 0.3968254 , 0.27020507],
        [0.23543441, 0.3968254 , 0.27020507],
        [0.18330494, 0.3968254 , 0.27020507],
        [0.18330494, 0.41269841, 0.2840772 ],
        [0.18330494, 0.41269841, 0.2973462 ],
        [0.20068143, 0.42063492, 0.31121834],
        [0.22964225, 0.42857143, 0.31121834],
        [0.31073254, 0.44444444, 0.27020507],
        [0.3802385 , 0.46825397, 0.22979493],
        [0.39761499, 0.50793651, 0.17551267],
        [0.39761499, 0.52380952, 0.17551267],
        [0.39761499, 0.53968254, 0.17551267],
        [0.42657581, 0.53968254, 0.1893848 ],
        [0.48449744, 0.58730159, 0.21652593],
        [0.53662692, 0.67460317, 0.21652593],
        [0.55400341, 0.71428571, 0.16887817],
        [0.58875639, 0.73015873, 0.16224367],
        [0.65826235, 0.82539683, 0.13510253],
        [0.65826235, 0.85714286, 0.08082027],
        [0.68143101, 0.87301587, 0.0946924 ],
        [0.76252129, 0.9047619 , 0.0946924 ],
        [0.77410562, 0.93650794, 0.0946924 ],
        [0.9362862 , 0.98412698, 0.0946924 ],
        [0.97103918, 0.98412698, 0.14837153],
        [0.94787053, 1.        , 0.14837153],
        [0.9362862 , 0.96825397, 0.013269  ],
        [0.95945486, 0.96825397, 0.013269  ],
        [0.97103918, 0.97619048, 0.013269  ],
        [0.97103918, 0.97619048, 0.08082027],
        [1.        , 0.97619048, 0.04041013],
        [1.        , 0.91564116, 0.04041013],
        [1.        , 0.93080078, 0.013269  ],
        [1.        , 0.96112003, 0.        ],
        [0.86678024, 0.91564116, 0.02714113],
        [0.33390119, 0.86258249, 0.3920386 ],
        [0.21805792, 0.80952381, 0.33835947],
        [0.18330494, 0.79436419, 0.2973462 ],
        [0.16013629, 0.68824683, 0.3787696 ],
        [0.17751278, 0.58212948, 0.3920386 ],
        [0.22964225, 0.55939005, 0.40591074],
        [0.20647359, 0.55181024, 0.44632087],
        [0.21805792, 0.55181024, 0.52774427],
        [0.28756388, 0.50633137, 0.5814234 ],
        [0.28756388, 0.44569288, 0.59529554],
        [0.27597956, 0.3850544 , 0.60856454],
        [0.26439523, 0.33957553, 0.59529554],
        [0.24122658, 0.3168361 , 0.5681544 ],
        [0.24701874, 0.3168361 , 0.5681544 ],
        [0.24701874, 0.30925629, 0.5681544 ],
        [0.27018739, 0.30925629, 0.5548854 ],
        [0.25860307, 0.30925629, 0.5548854 ],
        [0.26439523, 0.30925629, 0.50060314],
        [0.26439523, 0.33199572, 0.50060314],
        [0.2528109 , 0.35473515, 0.52774427],
        [0.24122658, 0.36231496, 0.50060314],
        [0.19488927, 0.36231496, 0.50060314],
        [0.20647359, 0.35473515, 0.50060314],
        [0.20647359, 0.33957553, 0.50060314],
        [0.20647359, 0.33957553, 0.52774427],
        [0.19488927, 0.32820581, 0.5548854 ],
        [0.19488927, 0.32441591, 0.60856454],
        [0.19488927, 0.30167648, 0.60856454],
        [0.19488927, 0.29409666, 0.60856454],
        [0.19488927, 0.27893704, 0.60856454],
        [0.18330494, 0.27893704, 0.60856454],
        [0.17172061, 0.27893704, 0.60856454],
        [0.17172061, 0.27893704, 0.60856454],
        [0.13696763, 0.2486178 , 0.60856454],
        [0.1253833 , 0.24103799, 0.6495778 ],
        [0.1253833 , 0.23345818, 0.70325694],
        [0.1253833 , 0.21071874, 0.71712907],
        [0.1253833 , 0.19555912, 0.71712907],
        [0.11379898, 0.19555912, 0.71712907],
        [0.13696763, 0.18797931, 0.73039807],
        [0.11243612, 0.17281969, 0.7575392 ],
        [0.10221465, 0.17281969, 0.7575392 ],
        [0.10221465, 0.16523988, 0.74427021],
        [0.08177172, 0.16523988, 0.74427021],
        [0.07155026, 0.16523988, 0.71712907],
        [0.06643952, 0.16523988, 0.71712907],
        [0.06643952, 0.16523988, 0.73039807],
        [0.06132879, 0.15766007, 0.7575392 ],
        [0.06132879, 0.15766007, 0.78468034],
        [0.06132879, 0.15766007, 0.79794934],
        [0.05621806, 0.15766007, 0.79794934],
        [0.05621806, 0.15766007, 0.79794934],
        [0.06132879, 0.15766007, 0.79794934],
        [0.07155026, 0.16523988, 0.79794934],
        [0.07155026, 0.17281969, 0.79794934],
        [0.07155026, 0.1803995 , 0.79794934],
        [0.07155026, 0.1803995 , 0.79794934],
        [0.07155026, 0.18797931, 0.79794934],
        [0.07155026, 0.20313893, 0.82509047],
        [0.08688245, 0.21829856, 0.82509047],
        [0.10221465, 0.25619761, 0.5199035 ],
        [0.11243612, 0.27135723, 0.50844391],
        [0.11243612, 0.27135723, 0.50844391],
        [0.12265758, 0.30167648, 0.50844391],
        [0.13287905, 0.30925629, 0.50844391],
        [0.18398637, 0.3168361 , 0.50844391],
        [0.18398637, 0.33199572, 0.50844391],
        [0.16354344, 0.33957553, 0.50844391],
        [0.13287905, 0.33199572, 0.50844391],
        [0.13287905, 0.30925629, 0.50844391],
        [0.13287905, 0.30167648, 0.73944511],
        [0.13798978, 0.29788657, 0.73944511],
        [0.12265758, 0.28651685, 0.73944511],
        [0.10221465, 0.27893704, 0.73944511],
        [0.09199319, 0.27893704, 0.73944511],
        [0.09199319, 0.27135723, 0.73944511],
        [0.06132879, 0.2486178 , 0.73944511],
        [0.06132879, 0.2486178 , 0.73944511],
        [0.05110733, 0.24103799, 0.73944511],
        [0.04088586, 0.21829856, 0.73944511],
        [0.04088586, 0.20313893, 0.73944511],
        [0.03577513, 0.20313893, 0.73944511],
        [0.03577513, 0.19555912, 0.73944511],
        [0.03577513, 0.18797931, 0.73944511],
        [0.03577513, 0.17281969, 0.73944511],
        [0.02044293, 0.16523988, 0.73944511],
        [0.0153322 , 0.15766007, 0.73944511],
        [0.        , 0.15766007, 0.67430639],
        [0.        , 0.15008026, 0.67430639],
        [0.        , 0.14250045, 0.67430639],
        [0.01022147, 0.14250045, 0.67430639],
        [0.01022147, 0.12734082, 0.67430639],
        [0.01022147, 0.09702158, 0.67430639],
        [0.01022147, 0.09702158, 0.67430639],
        [0.01022147, 0.09323167, 0.67430639],
        [0.01022147, 0.09702158, 0.67430639],
        [0.01022147, 0.09702158, 0.67430639],
        [0.01022147, 0.09702158, 0.67430639],
        [0.01022147, 0.09702158, 0.72677925],
        [0.0229983 , 0.09702158, 0.7424608 ],
        [0.0229983 , 0.09702158, 0.7575392 ],
        [0.05110733, 0.09702158, 0.77261761],
        [0.06132879, 0.10460139, 0.78769602],
        [0.06132879, 0.10460139, 0.80277443],
        [0.06132879, 0.10460139, 0.80277443],
        [0.07155026, 0.10460139, 0.80277443],
        [0.08177172, 0.10460139, 0.80277443],
        [0.08177172, 0.10460139, 0.80277443],
        [0.06132879, 0.1121812 , 0.80277443],
        [0.05621806, 0.12734082, 0.80277443],
        [0.06132879, 0.12734082, 0.80277443],
        [0.07155026, 0.12734082, 0.80277443],
        [0.08688245, 0.13492063, 0.80277443],
        [0.08688245, 0.15766007, 0.80277443],
        [0.08688245, 0.17281969, 0.80277443],
        [0.08688245, 0.1803995 , 0.80277443],
        [0.09710392, 0.18797931, 0.80277443],
        [0.09710392, 0.18797931, 0.80277443],
        [0.09710392, 0.18797931, 0.70446321],
        [0.08688245, 0.20692884, 0.70446321],
        [0.08688245, 0.21829856, 0.56332931],
        [0.08177172, 0.21829856, 0.58383595],
        [0.08177172, 0.21829856, 0.48250905],
        [0.08177172, 0.23345818, 0.5681544 ],
        [0.07160833, 0.23345818, 0.61037394],
        [0.07160833, 0.23345818, 0.54583836],
        [0.06667183, 0.23345818, 0.56393245],
        [0.06667183, 0.23345818, 0.6694813 ],
        [0.06667183, 0.23345818, 0.61278649],
        [0.06667183, 0.23345818, 0.63811821],
        [0.06667183, 0.23345818, 0.90651387],
        [0.06667183, 0.22587837, 0.68516285],
        [0.06667183, 0.21829856, 0.71049457],
        [0.06173533, 0.21071874, 0.76477684],
        [0.06173533, 0.21071874, 0.70386007],
        [0.05679882, 0.21071874, 0.67671894],
        [0.05679882, 0.21071874, 0.66706876],
        [0.05679882, 0.20692884, 0.66465621],
        [0.05679882, 0.19555912, 0.59348613],
        [0.04198931, 0.1803995 , 0.63329312],
        [0.05186232, 0.1803995 , 0.43425814],
        [0.05186232, 0.16523988, 0.60313631],
        [0.05433057, 0.16523988, 0.82810615],
        [0.05433057, 0.16523988, 0.73703257],
        [0.05433057, 0.16523988, 1.        ],
        [0.05433057, 0.16523988, 0.90651387],
        [0.05433057, 0.16523988, 0.95597105],
        [0.08148134, 0.18797931, 0.74185766],
        [0.08888609, 0.21071874, 0.78226779],
        [0.10122735, 0.24103799, 0.95114596],
        [0.10616385, 0.27135723, 0.67370326],
        [0.10616385, 0.30925629, 0.69119421],
        [0.13084637, 0.35473515, 0.61399276],
        [0.13084637, 0.36231496, 0.75150784],
        [0.13578287, 0.36231496, 0.66767189],
        [0.14071937, 0.37368468, 0.47768396],
        [0.15552888, 0.37368468, 0.94752714],
        [0.13578287, 0.37368468, 0.91737033],
        [0.13578287, 0.37747459, 0.85102533],
        [0.11603686, 0.37747459, 0.72738239],
        [0.13084637, 0.3850544 , 0.7840772 ],
        [0.13084637, 0.39263421, 0.75452352],
        [0.15059238, 0.40779383, 0.58866104],
        [0.16540189, 0.41537364, 0.60072376],
        [0.16540189, 0.43053326, 0.76176116],
        [0.15059238, 0.43811307, 0.65560917],
        [0.13084637, 0.43811307, 0.69662244],
        [0.11603686, 0.43053326, 0.69179735],
        [0.11603686, 0.41537364, 0.56272618],
        [0.10616385, 0.39263421, 0.80277443],
        [0.11110036, 0.37747459, 0.83775633],
        [0.11110036, 0.37747459, 0.78347407],
        [0.11110036, 0.3850544 , 0.63691194],
        [0.13084637, 0.39263421, 0.69240048],
        [0.13578287, 0.39642411, 0.62484922],
        [0.12590987, 0.41537364, 0.513269  ],
        [0.10616385, 0.42295345, 0.41495778],
        [0.11110036, 0.42295345, 0.39806996],
        [0.12097336, 0.43053326, 0.52895054]]),
 array([[0.05134015, 0.04761905],
        [0.05134015, 0.05555556],
        [0.05877342, 0.05555556],
        [0.05877342, 0.05555556],
        [0.04883021, 0.06349206],
        [0.04390687, 0.05555556],
        [0.04390687, 0.07142857],
        [0.05877342, 0.07936508],
        [0.06369676, 0.07936508],
        [0.05877342, 0.0952381 ],
        [0.05877342, 0.1031746 ],
        [0.05877342, 0.1031746 ],
        [0.04883021, 0.0952381 ],
        [0.04883021, 0.0952381 ],
        [0.04883021, 0.11904762],
        [0.04883021, 0.1031746 ],
        [0.04883021, 0.1031746 ],
        [0.05385009, 0.11111111],
        [0.04883021, 0.11111111],
        [0.02904032, 0.03968254],
        [0.02904032, 0.05555556],
        [0.02653038, 0.05555556],
        [0.04429302, 0.04761905],
        [0.04429302, 0.03174603],
        [0.04429302, 0.02380952],
        [0.0471891 , 0.01984127],
        [0.0471891 , 0.01984127],
        [0.0471891 , 0.00793651],
        [0.0471891 , 0.00793651],
        [0.0471891 , 0.00793651],
        [0.0471891 , 0.        ],
        [0.0471891 , 0.        ],
        [0.0471891 , 0.01587302],
        [0.04429302, 0.02380952],
        [0.05008518, 0.03174603],
        [0.05587734, 0.03571429],
        [0.06166951, 0.05555556],
        [0.06166951, 0.06349206],
        [0.07325383, 0.07142857],
        [0.07325383, 0.07142857],
        [0.07325383, 0.07142857],
        [0.07325383, 0.07142857],
        [0.10221465, 0.07936508],
        [0.10221465, 0.1031746 ],
        [0.11379898, 0.13492063],
        [0.16013629, 0.15079365],
        [0.17172061, 0.22222222],
        [0.18330494, 0.22222222],
        [0.28756388, 0.25396825],
        [0.29914821, 0.25396825],
        [0.29914821, 0.29365079],
        [0.28756388, 0.34920635],
        [0.2528109 , 0.33333333],
        [0.20068143, 0.34920635],
        [0.24122658, 0.37301587],
        [0.27597956, 0.3968254 ],
        [0.29914821, 0.42857143],
        [0.29914821, 0.46031746],
        [0.33390119, 0.47619048],
        [0.33390119, 0.47619048],
        [0.39182283, 0.50793651],
        [0.41499148, 0.50793651],
        [0.41499148, 0.53968254],
        [0.41499148, 0.53968254],
        [0.39182283, 0.53968254],
        [0.38255537, 0.44444444],
        [0.32810903, 0.44444444],
        [0.30494037, 0.4047619 ],
        [0.30494037, 0.3968254 ],
        [0.30494037, 0.3968254 ],
        [0.30494037, 0.3968254 ],
        [0.2528109 , 0.3968254 ],
        [0.23543441, 0.3968254 ],
        [0.18330494, 0.3968254 ],
        [0.18330494, 0.41269841],
        [0.18330494, 0.41269841],
        [0.20068143, 0.42063492],
        [0.22964225, 0.42857143],
        [0.31073254, 0.44444444],
        [0.3802385 , 0.46825397],
        [0.39761499, 0.50793651],
        [0.39761499, 0.52380952],
        [0.39761499, 0.53968254],
        [0.42657581, 0.53968254],
        [0.48449744, 0.58730159],
        [0.53662692, 0.67460317],
        [0.55400341, 0.71428571],
        [0.58875639, 0.73015873],
        [0.65826235, 0.82539683],
        [0.65826235, 0.85714286],
        [0.68143101, 0.87301587],
        [0.76252129, 0.9047619 ],
        [0.77410562, 0.93650794],
        [0.9362862 , 0.98412698],
        [0.97103918, 0.98412698],
        [0.94787053, 1.        ],
        [0.9362862 , 0.96825397],
        [0.95945486, 0.96825397],
        [0.97103918, 0.97619048],

In [22]:
norm_Xs_df = []
norm_Xs_test_df = []
for i in range(features_group_size):
    norm_Xs_df.append(pd.DataFrame(norm_Xs[i], columns=Xs[i].columns))
    norm_Xs_test_df.append(pd.DataFrame(norm_Xs_test[i], columns=Xs_test[i].columns))
    display(norm_Xs_df[-1])
    display(norm_Xs_test_df[-1])

,47027,30213,59288,14392,19597,45086,12437,540732,46204,534435,...,548450,19671,22807,548454,546255,22828,547449,10509791,545629,10952
0,0.051340,0.000000,0.047619,0.947034,0.057800,0.025482,0.735253,0.890456,0.133687,0.000000,...,0.194429,0.000000,0.032182,0.679191,0.029290,0.001800,1.000000,0.783474,0.124914,0.512098
1,0.051340,0.002082,0.055556,0.989407,0.076931,0.030894,0.776599,0.887092,0.063051,0.018787,...,0.114511,0.004284,0.026116,0.627861,0.029290,0.000000,0.912688,0.764777,0.179434,0.547235
2,0.058773,0.002688,0.055556,1.000000,0.076610,0.028679,0.796235,0.892010,0.121100,0.028968,...,0.199453,0.002203,0.050548,0.704855,0.029290,0.000675,0.912688,0.746080,0.062457,0.578265
3,0.058773,0.004060,0.055556,1.000000,0.035846,0.029818,0.786728,0.891900,0.081193,0.037998,...,0.151294,0.001224,0.033193,0.672774,0.027140,0.003151,0.877763,0.722557,0.117322,0.625637
4,0.048830,0.005401,0.063492,1.000000,0.074395,0.026652,0.819158,0.897969,0.050049,0.061572,...,0.231405,0.012240,0.014153,0.711271,0.027140,0.010127,0.877763,0.723764,0.067978,0.703357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,0.135783,0.986175,0.396424,0.703390,0.554442,0.092498,0.183729,0.494183,0.181224,0.109509,...,0.486997,0.650551,0.922494,0.303331,1.000000,0.817112,0.709806,0.624849,1.000000,0.941537
280,0.125910,0.990193,0.415374,0.735169,0.489337,0.082357,0.198867,0.499339,0.225322,0.114902,...,0.672766,0.627295,0.926369,0.341419,0.940797,0.859869,0.664707,0.513269,0.906487,1.000000
281,0.106164,0.993514,0.422953,0.779661,0.483192,0.081510,0.208167,0.504950,0.331595,0.115751,...,0.743595,0.566707,0.890817,0.320188,0.965725,0.833765,0.657479,0.414958,0.694962,0.992873
282,0.111100,0.997075,0.422953,0.830508,0.527651,0.089235,0.188419,0.509687,0.159592,0.117205,...,0.887239,0.575887,0.894356,0.350023,0.947029,0.831964,0.665352,0.398070,0.679089,0.899409
283,0.120973,1.000000,0.430533,0.872881,0.570078,0.088450,0.215936,0.515191,0.115356,0.115084,...,0.875821,0.507956,0.963269,0.336260,0.906522,0.839616,0.589654,0.528951,0.697032,0.935542

,47027,30213,59288,14392,19597,45086,12437,540732,46204,534435,...,548450,19671,22807,548454,546255,22828,547449,10509791,545629,10952
0,0.059920,0.000000,0.000000,1.0,0.990231,0.000000,1.000000,0.000000,0.294246,0.329193,...,0.511369,1.000000,0.826590,0.718926,0.286885,0.303249,1.000000,1.000000,0.729187,1.000000
1,0.000000,0.200583,0.208333,1.0,0.000000,0.075893,0.208044,0.208006,1.000000,0.304348,...,0.180602,0.844884,0.961464,0.689672,0.000000,1.000000,0.571400,0.029487,1.000000,0.017766
2,0.531292,0.422137,0.270833,1.0,0.387054,0.385980,0.468001,0.440207,0.000000,1.000000,...,0.000000,0.658966,0.000000,0.000000,0.344262,0.000000,0.000000,0.000000,0.413397,0.000000
3,1.000000,0.579880,0.500000,1.0,1.000000,0.476688,0.724193,0.627453,0.391938,0.291925,...,0.311247,0.477448,0.181118,0.776483,0.762295,0.592058,0.044867,0.153846,0.190431,0.723609
4,0.941411,0.775057,1.000000,1.0,0.491654,0.622335,0.654844,0.803612,0.933761,0.000000,...,0.779461,0.301430,0.412331,0.786609,1.000000,0.198556,0.406121,0.332051,0.000000,0.156300
5,0.941411,1.000000,1.000000,0.0,0.141810,1.000000,0.000000,1.000000,0.269058,0.608696,...,1.000000,0.000000,1.000000,1.000000,0.745902,0.588448,0.628948,0.760256,0.097608,0.390342

,47027,30213,59288,14392,45086,12437,540732,46204,10722376,541454,...,22768,548450,22807,548454,546255,22828,547449,10509791,545629,10952
0,0.051340,0.000000,0.047619,0.947034,0.025482,0.735253,0.890456,0.133687,0.381550,0.046950,...,0.915788,0.194429,0.032182,0.679191,0.029290,0.001800,1.000000,0.783474,0.124914,0.512098
1,0.051340,0.002082,0.055556,0.989407,0.030894,0.776599,0.887092,0.063051,0.382288,0.046950,...,0.902922,0.114511,0.026116,0.627861,0.029290,0.000000,0.912688,0.764777,0.179434,0.547235
2,0.058773,0.002688,0.055556,1.000000,0.028679,0.796235,0.892010,0.121100,0.384502,0.046950,...,0.984795,0.199453,0.050548,0.704855,0.029290,0.000675,0.912688,0.746080,0.062457,0.578265
3,0.058773,0.004060,0.055556,1.000000,0.029818,0.786728,0.891900,0.081193,0.383764,0.046950,...,0.912279,0.151294,0.033193,0.672774,0.027140,0.003151,0.877763,0.722557,0.117322,0.625637
4,0.048830,0.005401,0.063492,1.000000,0.026652,0.819158,0.897969,0.050049,0.383764,0.047704,...,0.861985,0.231405,0.014153,0.711271,0.027140,0.010127,0.877763,0.723764,0.067978,0.703357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,0.135783,0.986175,0.396424,0.703390,0.092498,0.183729,0.494183,0.181224,0.391144,0.185059,...,0.093799,0.486997,0.922494,0.303331,1.000000,0.817112,0.709806,0.624849,1.000000,0.941537
280,0.125910,0.990193,0.415374,0.735169,0.082357,0.198867,0.499339,0.225322,0.548339,0.153253,...,0.154412,0.672766,0.926369,0.341419,0.940797,0.859869,0.664707,0.513269,0.906487,1.000000
281,0.106164,0.993514,0.422953,0.779661,0.081510,0.208167,0.504950,0.331595,0.441328,0.170216,...,0.174044,0.743595,0.890817,0.320188,0.965725,0.833765,0.657479,0.414958,0.694962,0.992873
282,0.111100,0.997075,0.422953,0.830508,0.089235,0.188419,0.509687,0.159592,0.543173,0.171159,...,0.157799,0.887239,0.894356,0.350023,0.947029,0.831964,0.665352,0.398070,0.679089,0.899409
283,0.120973,1.000000,0.430533,0.872881,0.088450,0.215936,0.515191,0.115356,0.449446,0.184352,...,0.045592,0.875821,0.963269,0.336260,0.906522,0.839616,0.589654,0.528951,0.697032,0.935542

,47027,30213,59288,14392,45086,12437,540732,46204,10722376,541454,...,22768,548450,22807,548454,546255,22828,547449,10509791,545629,10952
0,0.059920,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.294246,0.452632,1.000000,...,1.0000,0.511369,0.826590,0.718926,0.286885,0.303249,1.000000,1.000000,0.729187,1.000000
1,0.000000,0.200583,0.208333,1.0,0.075893,0.208044,0.208006,1.000000,0.642105,0.780287,...,0.4375,0.180602,0.961464,0.689672,0.000000,1.000000,0.571400,0.029487,1.000000,0.017766
2,0.531292,0.422137,0.270833,1.0,0.385980,0.468001,0.440207,0.000000,0.000000,0.000000,...,0.0000,0.000000,0.000000,0.000000,0.344262,0.000000,0.000000,0.000000,0.413397,0.000000
3,1.000000,0.579880,0.500000,1.0,0.476688,0.724193,0.627453,0.391938,1.000000,0.137232,...,0.3750,0.311247,0.181118,0.776483,0.762295,0.592058,0.044867,0.153846,0.190431,0.723609
4,0.941411,0.775057,1.000000,1.0,0.622335,0.654844,0.803612,0.933761,0.231579,0.465012,...,0.3125,0.779461,0.412331,0.786609,1.000000,0.198556,0.406121,0.332051,0.000000,0.156300
5,0.941411,1.000000,1.000000,0.0,1.000000,0.000000,1.000000,0.269058,0.859649,0.591807,...,0.1875,1.000000,1.000000,1.000000,0.745902,0.588448,0.628948,0.760256,0.097608,0.390342

,47027,30213,59288,14392,45086,12437,540732,46204,10722376,22788,22555,22539,38498,22768,22807,548454,547449,10509791,545629,10952
0,0.051340,0.000000,0.047619,0.947034,0.025482,0.735253,0.890456,0.133687,0.381550,0.553093,0.883843,0.227040,0.042300,0.915788,0.032182,0.679191,1.000000,0.783474,0.124914,0.512098
1,0.051340,0.002082,0.055556,0.989407,0.030894,0.776599,0.887092,0.063051,0.382288,0.549785,0.900791,0.190048,0.053815,0.902922,0.026116,0.627861,0.912688,0.764777,0.179434,0.547235
2,0.058773,0.002688,0.055556,1.000000,0.028679,0.796235,0.892010,0.121100,0.384502,0.616275,0.915109,0.160800,0.058212,0.984795,0.050548,0.704855,0.912688,0.746080,0.062457,0.578265
3,0.058773,0.004060,0.055556,1.000000,0.029818,0.786728,0.891900,0.081193,0.383764,0.595766,0.934792,0.126114,0.046043,0.912279,0.033193,0.672774,0.877763,0.722557,0.117322,0.625637
4,0.048830,0.005401,0.063492,1.000000,0.026652,0.819158,0.897969,0.050049,0.383764,0.612306,0.995834,0.067513,0.059416,0.861985,0.014153,0.711271,0.877763,0.723764,0.067978,0.703357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,0.135783,0.986175,0.396424,0.703390,0.092498,0.183729,0.494183,0.181224,0.391144,0.104631,0.755484,0.342418,0.581951,0.093799,0.922494,0.303331,0.709806,0.624849,1.000000,0.941537
280,0.125910,0.990193,0.415374,0.735169,0.082357,0.198867,0.499339,0.225322,0.548339,0.124181,0.763977,0.324696,0.603241,0.154412,0.926369,0.341419,0.664707,0.513269,0.906487,1.000000
281,0.106164,0.993514,0.422953,0.779661,0.081510,0.208167,0.504950,0.331595,0.441328,0.085246,0.800652,0.324923,0.606238,0.174044,0.890817,0.320188,0.657479,0.414958,0.694962,0.992873
282,0.111100,0.997075,0.422953,0.830508,0.089235,0.188419,0.509687,0.159592,0.543173,0.102547,0.826244,0.351192,0.609150,0.157799,0.894356,0.350023,0.665352,0.398070,0.679089,0.899409
283,0.120973,1.000000,0.430533,0.872881,0.088450,0.215936,0.515191,0.115356,0.449446,0.101042,0.830782,0.330925,0.609799,0.045592,0.963269,0.336260,0.589654,0.528951,0.697032,0.935542

,47027,30213,59288,14392,45086,12437,540732,46204,10722376,22788,22555,22539,38498,22768,22807,548454,547449,10509791,545629,10952
0,0.059920,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.294246,0.452632,0.105467,1.000000,0.000000,0.000000,1.0000,0.826590,0.718926,1.000000,1.000000,0.729187,1.000000
1,0.000000,0.200583,0.208333,1.0,0.075893,0.208044,0.208006,1.000000,0.642105,0.412402,0.716619,0.923797,0.098640,0.4375,0.961464,0.689672,0.571400,0.029487,1.000000,0.017766
2,0.531292,0.422137,0.270833,1.0,0.385980,0.468001,0.440207,0.000000,0.000000,0.000000,0.596557,0.607029,0.244222,0.0000,0.000000,0.000000,0.000000,0.000000,0.413397,0.000000
3,1.000000,0.579880,0.500000,1.0,0.476688,0.724193,0.627453,0.391938,1.000000,0.684181,0.679338,0.425393,0.605458,0.3750,0.181118,0.776483,0.044867,0.153846,0.190431,0.723609
4,0.941411,0.775057,1.000000,1.0,0.622335,0.654844,0.803612,0.933761,0.231579,0.898495,0.708032,0.482783,0.958878,0.3125,0.412331,0.786609,0.406121,0.332051,0.000000,0.156300
5,0.941411,1.000000,1.000000,0.0,1.000000,0.000000,1.000000,0.269058,0.859649,1.000000,0.000000,1.000000,1.000000,0.1875,1.000000,1.000000,0.628948,0.760256,0.097608,0.390342

,47027,30213,59288,14392,540732,46204,10722376,22788,22555,22539,38498,22768,22807,548454,10509791,545629,10952
0,0.051340,0.000000,0.047619,0.947034,0.890456,0.133687,0.381550,0.553093,0.883843,0.227040,0.042300,0.915788,0.032182,0.679191,0.783474,0.124914,0.512098
1,0.051340,0.002082,0.055556,0.989407,0.887092,0.063051,0.382288,0.549785,0.900791,0.190048,0.053815,0.902922,0.026116,0.627861,0.764777,0.179434,0.547235
2,0.058773,0.002688,0.055556,1.000000,0.892010,0.121100,0.384502,0.616275,0.915109,0.160800,0.058212,0.984795,0.050548,0.704855,0.746080,0.062457,0.578265
3,0.058773,0.004060,0.055556,1.000000,0.891900,0.081193,0.383764,0.595766,0.934792,0.126114,0.046043,0.912279,0.033193,0.672774,0.722557,0.117322,0.625637
4,0.048830,0.005401,0.063492,1.000000,0.897969,0.050049,0.383764,0.612306,0.995834,0.067513,0.059416,0.861985,0.014153,0.711271,0.723764,0.067978,0.703357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,0.135783,0.986175,0.396424,0.703390,0.494183,0.181224,0.391144,0.104631,0.755484,0.342418,0.581951,0.093799,0.922494,0.303331,0.624849,1.000000,0.941537
280,0.125910,0.990193,0.415374,0.735169,0.499339,0.225322,0.548339,0.124181,0.763977,0.324696,0.603241,0.154412,0.926369,0.341419,0.513269,0.906487,1.000000
281,0.106164,0.993514,0.422953,0.779661,0.504950,0.331595,0.441328,0.085246,0.800652,0.324923,0.606238,0.174044,0.890817,0.320188,0.414958,0.694962,0.992873
282,0.111100,0.997075,0.422953,0.830508,0.509687,0.159592,0.543173,0.102547,0.826244,0.351192,0.609150,0.157799,0.894356,0.350023,0.398070,0.679089,0.899409
283,0.120973,1.000000,0.430533,0.872881,0.515191,0.115356,0.449446,0.101042,0.830782,0.330925,0.609799,0.045592,0.963269,0.336260,0.528951,0.697032,0.935542

,47027,30213,59288,14392,540732,46204,10722376,22788,22555,22539,38498,22768,22807,548454,10509791,545629,10952
0,0.059920,0.000000,0.000000,1.0,0.000000,0.294246,0.452632,0.105467,1.000000,0.000000,0.000000,1.0000,0.826590,0.718926,1.000000,0.729187,1.000000
1,0.000000,0.200583,0.208333,1.0,0.208006,1.000000,0.642105,0.412402,0.716619,0.923797,0.098640,0.4375,0.961464,0.689672,0.029487,1.000000,0.017766
2,0.531292,0.422137,0.270833,1.0,0.440207,0.000000,0.000000,0.000000,0.596557,0.607029,0.244222,0.0000,0.000000,0.000000,0.000000,0.413397,0.000000
3,1.000000,0.579880,0.500000,1.0,0.627453,0.391938,1.000000,0.684181,0.679338,0.425393,0.605458,0.3750,0.181118,0.776483,0.153846,0.190431,0.723609
4,0.941411,0.775057,1.000000,1.0,0.803612,0.933761,0.231579,0.898495,0.708032,0.482783,0.958878,0.3125,0.412331,0.786609,0.332051,0.000000,0.156300
5,0.941411,1.000000,1.000000,0.0,1.000000,0.269058,0.859649,1.000000,0.000000,1.000000,1.000000,0.1875,1.000000,1.000000,0.760256,0.097608,0.390342

,47027,30213,59288,14392,540732,46204,22788,22539,38498,22768,22807,548454,10509791,10952
0,0.051340,0.000000,0.047619,0.947034,0.890456,0.133687,0.553093,0.227040,0.042300,0.915788,0.032182,0.679191,0.783474,0.512098
1,0.051340,0.002082,0.055556,0.989407,0.887092,0.063051,0.549785,0.190048,0.053815,0.902922,0.026116,0.627861,0.764777,0.547235
2,0.058773,0.002688,0.055556,1.000000,0.892010,0.121100,0.616275,0.160800,0.058212,0.984795,0.050548,0.704855,0.746080,0.578265
3,0.058773,0.004060,0.055556,1.000000,0.891900,0.081193,0.595766,0.126114,0.046043,0.912279,0.033193,0.672774,0.722557,0.625637
4,0.048830,0.005401,0.063492,1.000000,0.897969,0.050049,0.612306,0.067513,0.059416,0.861985,0.014153,0.711271,0.723764,0.703357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,0.135783,0.986175,0.396424,0.703390,0.494183,0.181224,0.104631,0.342418,0.581951,0.093799,0.922494,0.303331,0.624849,0.941537
280,0.125910,0.990193,0.415374,0.735169,0.499339,0.225322,0.124181,0.324696,0.603241,0.154412,0.926369,0.341419,0.513269,1.000000
281,0.106164,0.993514,0.422953,0.779661,0.504950,0.331595,0.085246,0.324923,0.606238,0.174044,0.890817,0.320188,0.414958,0.992873
282,0.111100,0.997075,0.422953,0.830508,0.509687,0.159592,0.102547,0.351192,0.609150,0.157799,0.894356,0.350023,0.398070,0.899409
283,0.120973,1.000000,0.430533,0.872881,0.515191,0.115356,0.101042,0.330925,0.609799,0.045592,0.963269,0.336260,0.528951,0.935542

,47027,30213,59288,14392,540732,46204,22788,22539,38498,22768,22807,548454,10509791,10952
0,0.059920,0.000000,0.000000,1.0,0.000000,0.294246,0.105467,0.000000,0.000000,1.0000,0.826590,0.718926,1.000000,1.000000
1,0.000000,0.200583,0.208333,1.0,0.208006,1.000000,0.412402,0.923797,0.098640,0.4375,0.961464,0.689672,0.029487,0.017766
2,0.531292,0.422137,0.270833,1.0,0.440207,0.000000,0.000000,0.607029,0.244222,0.0000,0.000000,0.000000,0.000000,0.000000
3,1.000000,0.579880,0.500000,1.0,0.627453,0.391938,0.684181,0.425393,0.605458,0.3750,0.181118,0.776483,0.153846,0.723609
4,0.941411,0.775057,1.000000,1.0,0.803612,0.933761,0.898495,0.482783,0.958878,0.3125,0.412331,0.786609,0.332051,0.156300
5,0.941411,1.000000,1.000000,0.0,1.000000,0.269058,1.000000,1.000000,1.000000,0.1875,1.000000,1.000000,0.760256,0.390342

,47027,59288,14392,540732,46204,22788,38498,548454,10509791
0,0.051340,0.047619,0.947034,0.890456,0.133687,0.553093,0.042300,0.679191,0.783474
1,0.051340,0.055556,0.989407,0.887092,0.063051,0.549785,0.053815,0.627861,0.764777
2,0.058773,0.055556,1.000000,0.892010,0.121100,0.616275,0.058212,0.704855,0.746080
3,0.058773,0.055556,1.000000,0.891900,0.081193,0.595766,0.046043,0.672774,0.722557
4,0.048830,0.063492,1.000000,0.897969,0.050049,0.612306,0.059416,0.711271,0.723764
...,...,...,...,...,...,...,...,...,...
279,0.135783,0.396424,0.703390,0.494183,0.181224,0.104631,0.581951,0.303331,0.624849
280,0.125910,0.415374,0.735169,0.499339,0.225322,0.124181,0.603241,0.341419,0.513269
281,0.106164,0.422953,0.779661,0.504950,0.331595,0.085246,0.606238,0.320188,0.414958
282,0.111100,0.422953,0.830508,0.509687,0.159592,0.102547,0.609150,0.350023,0.398070
283,0.120973,0.430533,0.872881,0.515191,0.115356,0.101042,0.609799,0.336260,0.528951

,47027,59288,14392,540732,46204,22788,38498,548454,10509791
0,0.059920,0.000000,1.0,0.000000,0.294246,0.105467,0.000000,0.718926,1.000000
1,0.000000,0.208333,1.0,0.208006,1.000000,0.412402,0.098640,0.689672,0.029487
2,0.531292,0.270833,1.0,0.440207,0.000000,0.000000,0.244222,0.000000,0.000000
3,1.000000,0.500000,1.0,0.627453,0.391938,0.684181,0.605458,0.776483,0.153846
4,0.941411,1.000000,1.0,0.803612,0.933761,0.898495,0.958878,0.786609,0.332051
5,0.941411,1.000000,0.0,1.000000,0.269058,1.000000,1.000000,1.000000,0.760256

        47027     59288  10509791
0    0.051340  0.047619  0.783474
1    0.051340  0.055556  0.764777
2    0.058773  0.055556  0.746080
3    0.058773  0.055556  0.722557
4    0.048830  0.063492  0.723764
..        ...       ...       ...
279  0.135783  0.396424  0.624849
280  0.125910  0.415374  0.513269
281  0.106164  0.422953  0.414958
282  0.111100  0.422953  0.398070
283  0.120973  0.430533  0.528951

[284 rows x 3 columns]

      47027     59288  10509791
0  0.059920  0.000000  1.000000
1  0.000000  0.208333  0.029487
2  0.531292  0.270833  0.000000
3  1.000000  0.500000  0.153846
4  0.941411  1.000000  0.332051
5  0.941411  1.000000  0.760256

        47027     59288
0    0.051340  0.047619
1    0.051340  0.055556
2    0.058773  0.055556
3    0.058773  0.055556
4    0.048830  0.063492
..        ...       ...
279  0.135783  0.396424
280  0.125910  0.415374
281  0.106164  0.422953
282  0.111100  0.422953
283  0.120973  0.430533

[284 rows x 2 columns]

      47027     59288
0  0.059920  0.000000
1  0.000000  0.208333
2  0.531292  0.270833
3  1.000000  0.500000
4  0.941411  1.000000
5  0.941411  1.000000

        47027
0    0.051340
1    0.051340
2    0.058773
3    0.058773
4    0.048830
..        ...
279  0.135783
280  0.125910
281  0.106164
282  0.111100
283  0.120973

[284 rows x 1 columns]

      47027
0  0.059920
1  0.000000
2  0.531292
3  1.000000
4  0.941411
5  0.941411

### Then the normalized data split into <font color="blue">X_train and X_test (from test set)</font>, and
### <font color="blue">y_test (from test set data)</font>

In [24]:
# use the whole dataset for training
Xs_train = norm_Xs_df
# use test set for testing
Xs_test = norm_Xs_test_df

In [25]:
display(Xs_train[0])

,47027,30213,59288,14392,19597,45086,12437,540732,46204,534435,...,548450,19671,22807,548454,546255,22828,547449,10509791,545629,10952
0,0.051340,0.000000,0.047619,0.947034,0.057800,0.025482,0.735253,0.890456,0.133687,0.000000,...,0.194429,0.000000,0.032182,0.679191,0.029290,0.001800,1.000000,0.783474,0.124914,0.512098
1,0.051340,0.002082,0.055556,0.989407,0.076931,0.030894,0.776599,0.887092,0.063051,0.018787,...,0.114511,0.004284,0.026116,0.627861,0.029290,0.000000,0.912688,0.764777,0.179434,0.547235
2,0.058773,0.002688,0.055556,1.000000,0.076610,0.028679,0.796235,0.892010,0.121100,0.028968,...,0.199453,0.002203,0.050548,0.704855,0.029290,0.000675,0.912688,0.746080,0.062457,0.578265
3,0.058773,0.004060,0.055556,1.000000,0.035846,0.029818,0.786728,0.891900,0.081193,0.037998,...,0.151294,0.001224,0.033193,0.672774,0.027140,0.003151,0.877763,0.722557,0.117322,0.625637
4,0.048830,0.005401,0.063492,1.000000,0.074395,0.026652,0.819158,0.897969,0.050049,0.061572,...,0.231405,0.012240,0.014153,0.711271,0.027140,0.010127,0.877763,0.723764,0.067978,0.703357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,0.135783,0.986175,0.396424,0.703390,0.554442,0.092498,0.183729,0.494183,0.181224,0.109509,...,0.486997,0.650551,0.922494,0.303331,1.000000,0.817112,0.709806,0.624849,1.000000,0.941537
280,0.125910,0.990193,0.415374,0.735169,0.489337,0.082357,0.198867,0.499339,0.225322,0.114902,...,0.672766,0.627295,0.926369,0.341419,0.940797,0.859869,0.664707,0.513269,0.906487,1.000000
281,0.106164,0.993514,0.422953,0.779661,0.483192,0.081510,0.208167,0.504950,0.331595,0.115751,...,0.743595,0.566707,0.890817,0.320188,0.965725,0.833765,0.657479,0.414958,0.694962,0.992873
282,0.111100,0.997075,0.422953,0.830508,0.527651,0.089235,0.188419,0.509687,0.159592,0.117205,...,0.887239,0.575887,0.894356,0.350023,0.947029,0.831964,0.665352,0.398070,0.679089,0.899409
283,0.120973,1.000000,0.430533,0.872881,0.570078,0.088450,0.215936,0.515191,0.115356,0.115084,...,0.875821,0.507956,0.963269,0.336260,0.906522,0.839616,0.589654,0.528951,0.697032,0.935542

In [26]:
display(Xs_test[0])

,47027,30213,59288,14392,19597,45086,12437,540732,46204,534435,...,548450,19671,22807,548454,546255,22828,547449,10509791,545629,10952
0,0.059920,0.000000,0.000000,1.0,0.990231,0.000000,1.000000,0.000000,0.294246,0.329193,...,0.511369,1.000000,0.826590,0.718926,0.286885,0.303249,1.000000,1.000000,0.729187,1.000000
1,0.000000,0.200583,0.208333,1.0,0.000000,0.075893,0.208044,0.208006,1.000000,0.304348,...,0.180602,0.844884,0.961464,0.689672,0.000000,1.000000,0.571400,0.029487,1.000000,0.017766
2,0.531292,0.422137,0.270833,1.0,0.387054,0.385980,0.468001,0.440207,0.000000,1.000000,...,0.000000,0.658966,0.000000,0.000000,0.344262,0.000000,0.000000,0.000000,0.413397,0.000000
3,1.000000,0.579880,0.500000,1.0,1.000000,0.476688,0.724193,0.627453,0.391938,0.291925,...,0.311247,0.477448,0.181118,0.776483,0.762295,0.592058,0.044867,0.153846,0.190431,0.723609
4,0.941411,0.775057,1.000000,1.0,0.491654,0.622335,0.654844,0.803612,0.933761,0.000000,...,0.779461,0.301430,0.412331,0.786609,1.000000,0.198556,0.406121,0.332051,0.000000,0.156300
5,0.941411,1.000000,1.000000,0.0,0.141810,1.000000,0.000000,1.000000,0.269058,0.608696,...,1.000000,0.000000,1.000000,1.000000,0.745902,0.588448,0.628948,0.760256,0.097608,0.390342

In [27]:
y_train = y

### <b>(C) <u>Models Training And Predict</u></b>

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [30]:
# use more than 70% accuracy cfg and model from the research
DTR_params = {'ccp_alpha': 0.0,
        'criterion': 'squared_error', 'max_depth': None,
        'max_features': None, 'max_leaf_nodes': None,
        'min_impurity_decrease': 0.0, 'min_samples_leaf': 1,
        'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0,
        'monotonic_cst': None, 'random_state': 42, 'splitter': 'best'}

XG_params = {'objective': 'reg:squarederror', 'base_score': None,
             'booster': None, 'callbacks': None,
             'colsample_bylevel': None, 'colsample_bynode': None,
             'colsample_bytree': None, 'device': None,
             'early_stopping_rounds': None, 'enable_categorical': False,
             'eval_metric': None, 'feature_types': None, 'gamma': None,
             'grow_policy': None, 'importance_type': None, 'interaction_constraints': None,
             'learning_rate': None, 'max_bin': None, 'max_cat_threshold': None,
             'max_cat_to_onehot': None, 'max_delta_step': None, 'max_depth': None,
             'max_leaves': None, 'min_child_weight': None, 'missing': np.nan, 'monotone_constraints': None,
             'multi_strategy': None, 'n_estimators': None, 'n_jobs': None, 'num_parallel_tree': None,
             'random_state': 42, 'reg_alpha': None, 'reg_lambda': None, 'sampling_method': None,
             'scale_pos_weight': None, 'subsample': None, 'tree_method': None, 'validate_parameters': None, 'verbosity': None}

DTR_tune_params = {'ccp_alpha': 0.0, 'criterion': 'squared_error',
                   'max_depth': 5, 'max_features': None, 'max_leaf_nodes': None,
                   'min_impurity_decrease': 0.0, 'min_samples_leaf': 4, 'min_samples_split': 10,
                   'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'splitter': 'best'}

RF_params = {'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error',
             'max_depth': None, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None,
             'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0,
             'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

MLP_params = {'activation': 'relu', 'alpha': 0.0001, 'batch_size': 'auto',
                     'beta_1': 0.9, 'beta_2': 0.999, 'early_stopping': False, 'epsilon': 1e-08,
                     'hidden_layer_sizes': (100,), 'learning_rate': 'constant', 'learning_rate_init': 0.001,
                     'max_fun': 15000, 'max_iter': 30000, 'momentum': 0.9, 'n_iter_no_change': 10, 'nesterovs_momentum': True,
                     'power_t': 0.5, 'random_state': 42, 'shuffle': True, 'solver': 'adam', 'tol': 0.0001, 'validation_fraction': 0.1,
                     'verbose': False, 'warm_start': False}

models = {
    "Decision Tree": {
                        "model" : DecisionTreeRegressor(**DTR_params),                   
                        "acc" : "73.58",
                        "train_data" : Xs_train[0],                                      # index 0, use 0 thresold (all features)
                        "test_data" : Xs_test[0]
                     },
    # "MLP (Potential)": {
    #                     "model" : MLPRegressor(**MLP_params),                   
    #                     "acc" : "59.10",
    #                     "train_data" : Xs_train[3],                                      # index 3, use 0.3 thresold
    #                     "test_data" : Xs_test[3]
    #                     }
    # "XGBoost"     : {
    #                     "model" : XGBRegressor(**XG_params),                   
    #                     "acc" : "63.70",
    #                     "train_data" : Xs_train[2],                                      # index 2, use 0.2 threshold
    #                     "test_data" : Xs_test[2]
    #                  },
    # "Decision Tree (Tuned)" : {
    #                     "model" : DecisionTreeRegressor(**DTR_tune_params),                   
    #                     "acc" : "63.16",
    #                     "train_data" : Xs_train[0],                                      # index 0, use 0 thresold (all features)
    #                     "test_data" : Xs_test[0]
    #                  },
    # "Random Forest" : {
    #                     "model" : RandomForestRegressor(**RF_params),                   
    #                     "acc" : "62.47",
    #                     "train_data" : Xs_train[7],                                      # index 7, use 0.7 threshold
    #                     "test_data" : Xs_test[7]
    #                 },
}

In [31]:
date = ["20231101", "20240101", "20240301", "20240501", "20240701", "20240901"]
model_predict_table_md = "|model|Accuracy(%)|" + "|".join(date) + "\n"
model_predict_table_md += "|-|-|-|-|-|-|-|-|\n"

result_date_matrix = []

# Training by dataset, and testing by testset
for model_name, obj in models.items():
    
    # Train the model
    obj["model"].fit(obj["train_data"], y_train)
    
    # predictions
    y_pred = obj["model"].predict(obj["test_data"])

    result_date_matrix.append(y_pred)
    accuracy = obj["acc"]
    model_predict_table_md += (f"{model_name}|{accuracy}|" + "|".join(map(lambda x : f"{x:.4f}", y_pred)) + "\n")

In [32]:
result_date_matrix = np.vstack(result_date_matrix)
date_average_predict = np.mean(result_date_matrix, axis=0)

model_predict_table_md += "|-|-|-|-|-|-|-|-|\n"
model_predict_table_md += (f"Average|-|" + "|".join(map(lambda x : f"{x:.4f}", date_average_predict)))

In [33]:
import os
def export_csv(df, name):
    subdirectory = './predict_csv'
    # Get the current working directory
    current_directory = os.getcwd()
    export_path = os.path.join(current_directory, subdirectory)
    # Ensure the directory exists, if not, create it
    os.makedirs(export_path, exist_ok=True)
    df.to_csv(f'{export_path}/{name}_{dataset_name}.csv', index=False)

In [34]:
# export to a csv

df = pd.DataFrame({
    'Date': np.array(date),
    dataset_name: date_average_predict
})
export_csv(df, "predict")

In [35]:
display(Markdown(model_predict_table_md))

|model|Accuracy(%)|20231101|20240101|20240301|20240501|20240701|20240901
|-|-|-|-|-|-|-|-|
Decision Tree|73.58|12075.7273|20047.7200|16113.4300|6906.1000|119355.4300|119355.4300
|-|-|-|-|-|-|-|-|
Average|-|12075.7273|20047.7200|16113.4300|6906.1000|119355.4300|119355.4300